config/routes.rb
SalesCafe::Application.routes.draw do
  resources :reminders

  get 'home/index'
  match 'users/sign_up' => 'home#index', :via => [:get]
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks",:passwords => "passwords"}
  

  match "/contacts/:importer/contact_callback" => 'contacts#contact_callback', :via => [:get, :post]
  match 'import_contacts' => 'contacts#import_contacts', :via => [:get, :post]

  match '/contacts/failure' => 'contacts#import_failure'
  resources :settings
  post 'settings/save_group' => 'settings#save_group'
  post 'settings/delete_group' => 'settings#delete_group'
  post 'settings/delete_label' => 'settings#delete_label'
  post 'settings/get_group' => 'settings#get_group'
  post 'settings/save_source' => 'settings#save_source', :as => 'save_source'
  post 'settings/save_industry' => 'settings#save_industry', :as => 'save_industry'
  post 'settings/save_label' => 'settings#save_label', :as => 'save_label'
  post 'settings/save_user_label' => 'settings#save_user_label', :as => 'save_label'
  post 'settings/get_user_label' => 'settings#get_user_label'
  post 'settings/get_task_outcome_label' => 'settings#get_task_outcome_label'
  post 'settings/save_task_outcome_label' => 'settings#save_task_outcome_label'
  post 'settings/delete_taskoutcome' => 'settings#delete_taskoutcome'

  match '/update_weekly_digest' => 'settings#update_weekly_digest', :via => [:get, :post]
  match '/unscribe_latest_blog' => 'settings#unscribe_latest_blog', :via => [:get, :post]
  match 'settings/update_priority_org' => 'settings#update_priority_org', :via => [:get, :post]
  match 'settings/update_lead_status' => 'settings#update_deal_status', :via => [:get, :post]
  match 'settings/update_feed_keyword_org' => 'settings#update_feed_keyword_org', :via => [:get, :post]
  match 'settings/update_widget_org' => 'settings#update_widget_org', :via => [:get, :post]
  match 'settings/update_notification' => 'settings#update_notification', :via => [:get, :post]
  match 'settings/fetch_pages' => 'settings#fetch_pages', :via => [:get, :post]
  match 'update_org_settings' => 'settings#update_org_settings'
  match 'get_contacts/:org_id' => 'application#get_contacts'
  match 'settings/edit_source' => 'settings#edit_source'
  match 'settings/edit_industry' => 'settings#edit_industry'
  match 'edit_company_contact/:id' => 'contacts#edit_company_contact'
  match 'edit_individual_contact/:id' => 'contacts#edit_individual_contact'
  match 'getting_started' => 'home#getting_started'
  match 'daily_updates' => 'home#daily_updates'  
  match 'clear_cache' => 'home#clear_cache'
  match 'load_header_count_section' => 'home#load_header_count_section'
  match 'pie_donut_chart' => 'home#pie_donut_chart'
  match 'line_chart_display' => 'home#line_chart_display'
  match 'summary' => 'home#summary'
  match 'lead_statistics_info' => 'home#deal_statistics_info'
  match 'pie_chart_display' => 'home#pie_chart_display'
  match 'task_widget_page' => 'home#task_widget_page'
  match 'header_user_info' => 'application#header_user_info'
  match 'load_all_partials' => 'application#load_all_partials'
  match 'lead_contacts_info' => 'deals#deal_contacts_info'
  match 'created_by_user' => 'deals#created_by_user'
  match 'lead_location_filter' => 'deals#deal_location_filter'
  match 'assigned_lead_leaderboard' => 'deals#assigned_deal_leaderboard'
  match 'upload_multiple_note_attach' => 'deals#upload_multiple_note_attach'
  match 'delete_temp_note_attach' => 'deals#delete_temp_note_attach'
  match 'send_weekly_digest_email' => 'deals#send_weekly_digest_email'
  match 'leads/change_lead_status' => 'deals#change_lead_status'
  match 'get_lead_details_in_lead_listing' => 'deals#get_lead_details_in_lead_listing'
  match 'change_priority' => 'deals#change_priority'
  match 'change_user_label' => 'deals#change_user_label'
  match 'add_attchment_to_lead' => 'deals#add_attchment_to_lead'
  match 'get_lead_stages' => 'deals#get_lead_stages'
  match 'change_lead_stage' => 'deals#change_lead_stage'
  match 'change_lead_stage_in_lead_details' => 'deals#change_lead_stage_in_lead_details'
  match 'leads/kanban' => 'deals#index'
  match '/get_kanban_stages' => 'deals#get_kanban_stages', :via => [:post]
  match 'tab_settings_in_kanban' => 'deals#tab_settings_in_kanban', :via => [:post]

  

  authenticated :user do
    root :to => 'home#dashboard'
  end
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  match '/notfound' => 'home#notfound'

  match '/pricing' => 'home#index'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'
  match '/security' => 'home#security'
  match '/contact_us' => 'home#contact_us'
  match '/activities' => 'home#activities'
  match '/api_contact_us' => 'home#api_contact_us', :via => [:post]
  match '/bug_reports' => 'home#report_a_bug'
  match '/save_bug_report' => 'api#save_bug_report', :via => [:post]
  match '/show_bug_report/:id' => 'home#show_bug_report'
  match '/post_comment' => 'home#post_comment'
  match '/delete_emails' => 'deals#delete_emails'
  match '/archive_emails' => 'deals#archive_emails'

  get 'get_day_reminder' => 'reminders#get_day_reminder'
  get 'get_day_reminder' => 'home#dashboard'
  get 'dashboard' => 'home#dashboard', :as => 'dashboard'
  match '/task_widget' => 'home#task_widget'
  match '/lead_task_widget' => 'deals#deal_task_widget'
  match '/task_widget_reload' => 'deals#task_widget_reload'
  match '/get_activities' => 'home#get_activities'
  match '/usage' => 'home#usage'
  resources :contacts do
    get :autocomplete_first_name, :on => :collection

  end

  match 'add_contact_form' => 'contacts#add_contact_form', :via => [:post]
  match 'get_companies/:org_id' => 'application#get_companies'
  match 'company_contact/:id' => 'contacts#company_contact_detail'
  match 'individual_contact/:id' => 'contacts#individual_contact_detail'
  match 'contact/:id' => 'contacts#show_contact_detail'
  resources :contacts
  match 'contacts/change_status/:id' => 'contacts#change_status', :via => [:post]
  match 'get_all_contacts' => 'contacts#get_all_contacts', :via => [:GET]
  match 'get_more_contacts' => 'contacts#get_more_contacts', :via => [:post], :as => 'get_more_contacts'
  match 'contact_widget' => 'contacts#contact_widget', :via => [:post]
  match 'get_contact_ajax' => 'contacts#get_contact_ajax', :via => [:post]
  match 'save_contact_timezone' => 'contacts#save_contact_timezone'

  match 'imported_contacts' => 'contacts#imported_contacts', :via => [:get,:post] 
  match 'import_contact_from_sugar_crm' => 'contacts#import_contact_from_sugar_crm', :via => [:get,:post] 
  match 'import_contact_from_zoho_crm' => 'contacts#import_contact_from_zoho_crm', :via => [:get,:post] 
  match 'import_contact_from_fatfree_crm' => 'contacts#import_contact_from_fatfree_crm', :via => [:get,:post] 
  match 'import_contact_from_other_crm' => 'contacts#import_contact_from_other_crm', :via => [:get,:post] 
  match 'proceed_to_lead' => 'contacts#proceed_to_lead', :via => [:get] 
  match 'fetch_more_contacts' => 'contacts#fetch_more_contacts', :via => [:post], :as => 'get_more_contacts'
  
  resources :users
  match 'get_user_email' => 'users#get_user_email'
  match 'profile' => 'users#profile'
  match 'profile/:id' => 'users#profile'
  match 'assign_unassign_deals' => 'users#assign_unassign_deals', :via => [:post]
  match 'get_daily_update_form' => 'deals#get_daily_update_form', :via => [:get]
  match 'save_daily_updates' => 'users#save_daily_updates', :via => [:post]
  match 'manage_daily_updates' => 'users#manage_daily_updates'
  match 'edit_daily_update' => 'users#edit_daily_update'
  match 'delete_daily_update/:id' => 'users#delete_daily_update', :via => [:delete], :as => 'delete_daily_update'
  match '/create_admin_user' => 'users#create_admin_user', :via => [:post]

  match '/download_user' => 'home#download_user', :as => 'download_user'
  match 'source_list' => 'users#source_list', :as => 'source_list'
  match 'industry_list' => 'users#industry_list', :as => 'industry_list'
  match '/change_password' => 'users#change_password'
  match '/save_password' => 'users#save_password', :via => [:put]
  match 'invite_user' => 'users#invite_user'
  match 'invite_demo_user' => 'users#invite_demo_user'
  match 'get_source_list' => 'users#get_source_list', :via => [:post], :as => 'get_source_list'
  match 'get_industry_list' => 'users#get_industry_list', :via => [:post], :as => 'get_industry_list'
  match 'delete_source/:id' => 'users#delete_source'
  match 'delete_industry/:id' => 'users#delete_industry'
  match 'save_profile_info' => 'users#save_profile_info'
  match 'edit_user' => 'users#edit_user'
  match 'assign_deal_to_user' => 'users#assign_deal_to_user'
  match 'resend_invitation' => 'users#resend_invitation'
  match 'load_header_count_user' => 'users#load_header_count_user'
  match 'enable_user/:id' => 'users#enable_usr'
  match 'user_save_tmp_img' => 'users#save_tmp_img'
  match 'update_profile_image' => 'users#update_profile_image'
  match 'block_unblock_user' => 'users#block_unblock_user'
  match 'grant_revoke_admin' => 'users#grant_revoke_admin'
  match 'remove_lead' => 'users#remove_lead'

  resources :tasks
  match 'calendar_task' => 'tasks#calendar_task'
  match 'calendar_data' => 'tasks#calendar_data'
  match 'task_tab_data' => 'tasks#task_tab_data'

  match 'complete' => 'tasks#complete', :via => [:post]
  match 'edit_task' => 'tasks#edit_task'
  match 'follow_up_task' => 'tasks#follow_up_task'
  match 'start_task' => 'tasks#start_task', :via => [:post]
  match 'all_task' => 'tasks#all_task', :via => [:post]
  match 'today_task' => 'tasks#today_task', :via => [:post]
  match 'overdue_task' => 'tasks#overdue_task', :via => [:post]
  match 'upcoming_task' => 'tasks#upcoming_task', :via => [:post]
  match 'task_listing' => 'tasks#task_listing', :via => [:post]
  match 'task_filter' => 'tasks#task_filter', :via => [:post]

app/views/shared/_header.haml
= javascript_include_tag "https://secure.skypeassets.com/i/scom/js/skype-uri.js"
:javascript
  $(function(){
   $('a[rel="tooltip"],i,input:checkbox,button,div').powerTip({placement: 'n'});
   $(".slide_m").hide();
   $(".nav.navbar-nav li a").hover(function(){
     $(this).find(".slide_m").show('slide', { direction: 'right' }, 300);
   },function(){
     $(this).find(".slide_m").hide();
   });
   $('.f_menu').click(function() {
    //$(this).preventDefault();
    $(this).next('.dropdown-menu').toggle(100);
    //$(this).find('.dropdown-menu').stop(true, true).slideToggle(100);
    //e.preventDefault()
   });
  });
  function send_mail(){
    $('#task_loader').show();
    $.ajax( {
      type: "POST",
      url: "/send_latest_blog_mail" ,
      data: {},
      success: function(result) {
        $('#task_loader').hide();
        $(document).trigger("add-alerts", [{'message': "Latest blog mail sent successfully." ,'priority': 'success'}]);
      }
    });
  }  	  
  
/ - if user_signed_in?
/   .navbar.navbar-default{role: "navigation"}
/     = render :partial => "shared/top_header"
/ - else
%div
  %header.new_header
    %nav
      #stickyheader.top_menu_land
        .corner-icon
        #wrapper.menu_outer_hm
          .fl.logo_landing
            %span.b_lg
              %a{:href => "http://www.wakeupsales.org"}
                / <img src="http://www.wakeupsales.org/img/wakeup-salelogo.png"  alt="WakeUpSales CRM" title="WakeUpSales CRM"/>
                %span.wkps-logo-sprite.logo-2
                / <strong class="sb_ttl logo-sub-text">Open Source CRM Tool</strong>
          #nav-main.fl.top_land_menu
            %ul
              %li.how-hover.serv_smenu
                %a#show_slide_menu{:href => "javascript:void(0)", :style => "outline:none;"} Community
                / <span class="header-down-arw"></span>
                .how-sub-menu.osource_community.osource_installation
                  %span.arrow-img
                    %img{:alt => "arw_top", :src => "http://www.orangescrum.org/img/home/arw_top.png"}
                  %ul
                    %li
                      %a{:href => "https://groups.google.com/forum/#!forum/support_wakeupsales", :target => "_blank"} Community Forum
                    %li
                      %a{:href => "http://www.wakeupsales.org/faq", :style => "outline:none;", target: "_blank"} FAQ
              %li.how-hover.serv_smenu
                %a{:href => "http://www.wakeupsales.org/services", :style => "outline:none;", target: "_blank"} Services
              %li.how-hover.serv_smenu{:style => "margin: 0px 20px 0px -18px"}
                %sup.blink{:style => "color:#FF0000;cursor:text;top: -13px;left: 85px;position: relative;font-size: 10px;"}  New
                %a{:href => "http://www.wakeupsales.org/plugins", :style => "outline:none;", target: "_blank"} Plugins
              %li.how-hover.serv_smenu
                %a.i_guide_os{:href => "http://www.wakeupsales.org/installation_guide", :style => "outline:none;margin-left:-5px;", target: "_blank"} Installation Guide
                / <span class="header-down-arw"></span>
                .how-sub-menu.osource_community.osource_installation
                  %span.arrow-img
                    %img{:alt => "arw_top", :src => "http://www.orangescrum.org/img/home/arw_top.png"}/
                  %ul
                    %li
                      %a{:href => "http://www.wakeupsales.org/Setup-Linux", :style => "outline:none;", target: "_blank"} WakeUpSales on Linux
                    %li
                      %a{:href => "http://www.wakeupsales.org/Setup-Heroku", :style => "outline:none;", target: "_blank"} WakeUpSales on Heroku
                    %li
                      %a{:href => "http://www.wakeupsales.org/Setup-Windows", :style => "outline:none;", target: "_blank"} WakeUpSales on Windows
                    %li
                      %a{:href => "http://www.wakeupsales.org/Setup-Mac", :style => "outline:none;", target: "_blank"} WakeUpSales on Mac
                    %li
                      %a{:href => "http://www.wakeupsales.org/Setup-Docker", :style => "outline:none;", target: "_blank"} WakeUpSales on Docker
                    %li
                      %a{:href => "http://www.wakeupsales.org/customization", :style => "outline:none;", target: "_blank"} How to Customize
                    %li
                      %a{:href => "http://www.wakeupsales.org/Google-calender-installation-guide", :style => "outline:none;", target: "_blank"} How to Sync google calendar
              %li.how-hover.serv_smenu{:style => "margin-left: 5px;"}
                %a{:href => "http://www.wakeupsales.org/knowledge-base", :style => "outline:none;", target: "_blank"} Knowledge Base
              %li.how-hover.serv_smenu{:style => "margin-left: 5px;"}
                %a{:href => "http://blog.wakeupsales.com/", :style => "outline:none;", :target => "_blank"} Blog
              / %li.how-hover.serv_smenu.try-demo-btn
              /   %a{:href => "http://demo.wakeupsales.org", :style => "margin:0 10px;z-index: 999999;", :target => "_blank"} Try Demo
              /
                <li class=" how-hover serv_smenu contactus-btn">
                <a href="javascript:void(0)" id="tech_support">Support</a>
                </li>
              %li.skype-li
                .skype-os{:id => "SkypeButton_Call_andola.ankit_1"}
            #forgot_pwd_popup{style: "display:none"}
              = form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post, :class => "form-horizontal", :id=>"fpwd_form" }) do |f|
                = f.email_field :email, :required => true, :class=>"form-control", :placeholder=>"Email", :style=>""
                %br/
                %button.btn.btn-primary.btn-block{type: "submit"}
                  Send instructions
                = link_to "Sign In", "javascript:void(0)", :onclick => "$('#forgot_pwd_popup').hide();$('#signin_popup').show();$('#signin_form')[0].reset();"


= render partial: "home/import_contact_modal"

:javascript
  $(document).ready(function(){
    Skype.ui({
      "name": "dropdown",
      "element": "SkypeButton_Call_andola.ankit_1",
      "participants": ["andola.ankeet"]
    });
  });

app/views/shared/_header_user_info.haml
- if user_signed_in?
  - unless @current_user.is_siteadmin?
    %li
      .fl.sch_res_top{onclick: "sch_slide()"}
        = form_tag search_result_path, method: :get, id: "search_form", format: "json" do
          /.navbar-left.input-group#search_fld{style: "opacity:0.5"}
          .navbar-right.input-group
            = text_field_tag :query, params[:query], class: "form-control srch_fld",:required=> true
          .input-group-btn{style: "position:inherit;"}
            = submit_tag "", name: nil, class: "nav_srch_box", :disable_with => ""
    %li.dropdown.addData
      %a#notification_image.dropdown-toggle.image-effect{"data-toggle" => "dropdown", href: "#", style:"padding: 14px 7px 34px !important;"}
        .fl.icon-new-bell
        .fl
          New
        .fr.dwn_f_arrow
      %ul.pull-right.dropdown-menu.dropdown-caret.dropdown-close{style: "padding:0"}
        %li
          =link_to "#dealModal", "data-toggle" => "modal", "onclick" => "$('#new_deal')[0].reset();$('.error').html('');$('#deal_first_name').attr('disabled', false);" do
            =image_tag "deal_small.png",:alt=>"", :style=>"margin-right:10%"
            Deal
        %li.divider
        %li
          =link_to "#taskModal", "data-toggle" => "modal", "onclick" => "$('#task_form')[0].reset();$('#email_err').html('');$('.deal_list').show();$('.contact_firstname_div').hide();$('#deal_title').prop('required','true');$('#deal_title').removeAttr('disabled')" do
            =image_tag "tasks_small.png",:alt=>"", :style=>"margin-right:10%"
            Task
        %li.divider
        %li
          =link_to "#contactModal", "data-toggle" => "modal", "onclick" => "$('#new-contact')[0].reset();$('#email_err_i').html('');$('#company_added_info_div').css('display','none');display_company_div('hide')" do
            =image_tag "contact_small.png",:alt=>"", :style=>"margin-right:10%"
            Contact
        - if current_user.is_admin? || current_user.is_super_admin?
          %li.divider
          %li
            =link_to "#inviteuserModal","data-toggle" => "modal", "onclick" => "$('#user_invite_form')[0].reset();$('#email_err_usr').html('');" do
              /%img{:src=>"/assets/user_small.png",:alt=>"", :style=>"margin-right:10%"}
              %i.icon-group.icon-2x.green{:style=>"margin-right:10%"}
              Invite user
        %li.divider
    %input{:type=>"hidden",:id=>"session_authenticity_token",:value=>session[:_csrf_token]}
  - unless current_user.is_siteadmin?
    %li#bell_notification.dropdown
      = render partial: "shared/notification_section"
  %li.dropdown
    - if current_user.image.present? && current_user.image.image.present?
      = image_tag current_user.image.image.url(:thumb), :alt=>"profile image", :class=>"profile-circle fl"
    - else
      = image_tag "no_user30.png", :alt=>"dummy user", :class=>"img-circle fl"
    %a.fr.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      .fl
        =current_user.full_name.blank? ? current_user.organization.name : current_user.full_name
      .fr.dwn_f_arrow
    %ul.dropdown-menu
      %li
        %div{style: "text-align:left;margin-left:20px"}
          %b 
            =current_user.full_name
          - unless current_user.is_siteadmin?
            %div{style: "font-size:13px"}
              =current_user.organization.name
      %li.divider
      /- if current_user.is_admin? || current_user.is_super_admin?
      - unless current_user.is_siteadmin?
        %li
          %a{href: "/settings"}
            %i.icon-cog{style: "margin-right:5px;"}
            Settings
        %li.divider
        %li
          =link_to profile_path do
            %i.icon-user{style: "margin-right:5px;"}
            Profile
        %li.divider
      %li
        =link_to change_password_path do
          %i.icon-lock{style: "margin-right:5px;"}
          Change Password
      %li.divider
      - if current_user.is_admin?  || current_user.is_super_admin?
        %li
          %a{href: "/users"}
            %i.glyphicon.glyphicon-tower{style: "margin-right:5px;"}
            Admin
        %li.divider
      %li
        %a{"data-method" => "delete", href: "/users/sign_out", rel: "nofollow"}
          %i.icon-off{style: "margin-right:5px;"}
          Logout
        /= link_to destroy_user_session_path, :method => :delete do
        /  %i.icon-off{style: "margin-right:5px;"}
        /    Logout
/ /.navbar-collapse

app/views/shared/_industry.haml
/=javascript_include_tag "bootstrap-formhelpers-phone.js"
#industryModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "industryModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content.col-md-9      
      .modal-body
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h3#industryModalLabel Add New Industry
        - industry = Industry.new
        = form_for(industry,:action=>save_industry_path,:url=>"/settings/save_industry", :remote => true, :html=>{:class => "form",:method=>"post",:id=>"new_industry"}) do |f|
          .row
            .form-group.col-md-8
              =f.text_field :name, :required => true ,:name=> "value",:class=> "col-md-8 form-control",:html=>{:maxlength=> "100"},:onblur =>"this.value = jQuery.trim((this.value).replace(/^\s*/g,''))", :style=> "resize: none;" 
              %label{id: "show_err_in",class: "error"}
            .form-group.col-md-2 
              %button.btn.btn-primary{type: "submit"} 
                %span.glyphicon.glyphicon-ok
            .form-group.col-md-2 
              %button.btn.btn-default{"aria-hidden" => "true", "data-dismiss" => "modal"}
                %span.glyphicon.glyphicon-remove





:javascript
  $(document).ready(function() { 
      var options = { 
          target:        '#output2',   // target element(s) to be updated with server response 
          beforeSubmit:  showRequestSource1,  // pre-submit callback 
          success:       showResponseSource1,  // post-submit callback 
      }; 
   
      // bind to the form's submit event 
      $('#new_industry').submit(function() {
           
            $(this).ajaxSubmit(options); 
           return false; 
      }); 
  }); 
  function validatesource1()
  {
    if($("#industry_name").val() != "")
      return true;
    else
      return false;
  }
  // pre-submit callback 
  function showRequestSource1(formData, jqForm, options) { 
      // formData is an array; here we use $.param to convert it to a string to display it 
      // but the form plugin does this for you automatically when it submits the data 
      var queryString = $.param(formData); 
   
      // jqForm is a jQuery object encapsulating the form element.  To access the 
      // DOM element for the form do this: 
      // var formElement = jqForm[0]; 
   
      //alert('About to submit: \n\n' + queryString); 
   
      // here we could return false to prevent the form from being submitted; 
      // returning anything other than false will allow the form submit to continue
      if(validatesource1() == true)         
        return true;
      else
        return false; 
  } 
   
  // post-submit callback 
  function showResponseSource1(responseText, statusText, xhr, $form)  { 
      // for normal html responses, the first argument to the success callback 
      // is the XMLHttpRequest object's responseText property 
   
      // if the ajaxSubmit method was passed an Options Object with the dataType 
      // property set to 'xml' then the first argument to the success callback 
      // is the XMLHttpRequest object's responseXML property 
   
      // if the ajaxSubmit method was passed an Options Object with the dataType 
      // property set to 'json' then the first argument to the success callback 
      // is the json data object returned by the server 
   
      //alert('status: ' + statusText + '\n\nresponseText: \n' + responseText + 
      //    '\n\nThe output div should have already been updated with the responseText.');
      var newsource = $($form).find("#industry_name").val();
      var o = new Option(newsource, responseText);
      /// jquerify the DOM object 'o' so we can use the html method
      if(responseText == "exists")
      {
       $("#show_err_in").html('Industry already exists.');
      }
      else
      {
      $("#show_err_in").html('');

      $(o).html(newsource);
      $(o).prop('selected', true)
      $("#deal_deal_source").append(o);
      $($form).find("#industry_name").val("");
      $("#industryModal").modal('hide');    
      window.location.href = "/users";
      }      
   }

app/views/shared/_invite_user.haml
/=javascript_include_tag "bootstrap-formhelpers-phone.js"
/ Invite user popup starts
#inviteuserModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.cstm-material-modal
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title invite a User
      .modal-body
        = form_for(User.new, :url => new_lead_path, :html=>{:class => "form"}) do |f|
          .row
            .form-group.col-md-6
              %label
                First Name
                %font{color: "red", size: "2"} *
              =f.text_field :first_name, :required => true,:html=>{:maxlength=> "20"}
            .form-group.col-md-6
              %label 
                Last Name
                %font{color: "red", size: "2"} *
              =f.text_field :last_name, :required => true,:html=>{:maxlength=> "20"}
          .row
            .form-group.col-md-6
              %label
                Email
                %font{color: "red", size: "2"} *
              =f.text_field :email, :required => true,:html=>{:maxlength=> "50"}
            .form-group.col-md-6    
              %label 
                Work Phone
                %font{color: "red", size: "2"} *
              .input-group
                %span.input-group-addon +1
                /=f.text_field :work_phone,:class=>"col-md-12 form-control bfh-phone",:type=>"phone","data-format"=>"(ddd) ddd-dddd","data-number"=>"15555555555",:placeholder=>"(999) 999 9999", :required => true
          .row
            .form-group.col-md-6
              %label Time Zone
              /= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, { :class => 'form-control' }, :required => true
              /= f.select "admin_type", options_from_collection_for_select(current_user.organization.roles.all, "id","name"), { :include_blank=>true }
            .form-group.col-md-6
              %label 
                User Group
                %font{color: "red", size: "2"} *
              .radio
                %label
                  =f.radio_button :admin_type, "2", :checked => true, :onclick => "$('#show_dropdown').hide();"
                  Admin
              .radio
                %label
                  =f.radio_button :admin_type, "3", :onclick => "$('#show_dropdown').show();"
                  Non-Admin
                  %span#show_dropdown{style: "display:block"}
                    /=f.fields_for user_role do |r|
                    /  = r.select :role_id, options_from_collection_for_select(current_user.organization.roles.all, "id","name"), { :class => 'form-control' }
          .modal-footer
            /%button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
            =f.submit "Invite User", :class=>"btn.btn-primary"
:javascript
  $(window).on('load', function () {
    $('form input[type="text"].bfh-phone, form input[type="phone"].bfh-phone, span.bfh-phone').each(function () {
      var $phone = $(this);
      $phone.bfhphone($phone.data());
    });
    //$("#user_time_zone").addClass("col-md-12 form-control");
  });