config/routes.rb
SalesCafe::Application.routes.draw do
  resources :reminders

  get 'home/index'
  match 'users/sign_up' => 'home#index', :via => [:get]
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks",:passwords => "passwords"}
  

  match "/contacts/:importer/contact_callback" => 'contacts#contact_callback', :via => [:get, :post]
  match 'import_contacts' => 'contacts#import_contacts', :via => [:get, :post]

  match '/contacts/failure' => 'contacts#import_failure'
  resources :settings
  post 'settings/save_group' => 'settings#save_group'
  post 'settings/delete_group' => 'settings#delete_group'
  post 'settings/delete_label' => 'settings#delete_label'
  post 'settings/get_group' => 'settings#get_group'
  post 'settings/save_source' => 'settings#save_source', :as => 'save_source'
  post 'settings/save_industry' => 'settings#save_industry', :as => 'save_industry'
  post 'settings/save_label' => 'settings#save_label', :as => 'save_label'
  post 'settings/save_user_label' => 'settings#save_user_label', :as => 'save_label'
  post 'settings/get_user_label' => 'settings#get_user_label'
  post 'settings/get_task_outcome_label' => 'settings#get_task_outcome_label'
  post 'settings/save_task_outcome_label' => 'settings#save_task_outcome_label'
  post 'settings/delete_taskoutcome' => 'settings#delete_taskoutcome'

  match '/update_weekly_digest' => 'settings#update_weekly_digest', :via => [:get, :post]
  match '/unscribe_latest_blog' => 'settings#unscribe_latest_blog', :via => [:get, :post]
  match 'settings/update_priority_org' => 'settings#update_priority_org', :via => [:get, :post]
  match 'settings/update_lead_status' => 'settings#update_deal_status', :via => [:get, :post]
  match 'settings/update_feed_keyword_org' => 'settings#update_feed_keyword_org', :via => [:get, :post]
  match 'settings/update_widget_org' => 'settings#update_widget_org', :via => [:get, :post]
  match 'settings/update_notification' => 'settings#update_notification', :via => [:get, :post]
  match 'settings/fetch_pages' => 'settings#fetch_pages', :via => [:get, :post]
  match 'update_org_settings' => 'settings#update_org_settings'
  match 'get_contacts/:org_id' => 'application#get_contacts'
  match 'settings/edit_source' => 'settings#edit_source'
  match 'settings/edit_industry' => 'settings#edit_industry'
  match 'edit_company_contact/:id' => 'contacts#edit_company_contact'
  match 'edit_individual_contact/:id' => 'contacts#edit_individual_contact'
  match 'getting_started' => 'home#getting_started'
  match 'daily_updates' => 'home#daily_updates'  
  match 'clear_cache' => 'home#clear_cache'
  match 'load_header_count_section' => 'home#load_header_count_section'
  match 'pie_donut_chart' => 'home#pie_donut_chart'
  match 'line_chart_display' => 'home#line_chart_display'
  match 'summary' => 'home#summary'
  match 'lead_statistics_info' => 'home#deal_statistics_info'
  match 'pie_chart_display' => 'home#pie_chart_display'
  match 'task_widget_page' => 'home#task_widget_page'
  match 'header_user_info' => 'application#header_user_info'
  match 'load_all_partials' => 'application#load_all_partials'
  match 'lead_contacts_info' => 'deals#deal_contacts_info'
  match 'created_by_user' => 'deals#created_by_user'
  match 'lead_location_filter' => 'deals#deal_location_filter'
  match 'assigned_lead_leaderboard' => 'deals#assigned_deal_leaderboard'
  match 'upload_multiple_note_attach' => 'deals#upload_multiple_note_attach'
  match 'delete_temp_note_attach' => 'deals#delete_temp_note_attach'
  match 'send_weekly_digest_email' => 'deals#send_weekly_digest_email'
  match 'leads/change_lead_status' => 'deals#change_lead_status'
  match 'get_lead_details_in_lead_listing' => 'deals#get_lead_details_in_lead_listing'
  match 'change_priority' => 'deals#change_priority'
  match 'change_user_label' => 'deals#change_user_label'
  match 'add_attchment_to_lead' => 'deals#add_attchment_to_lead'
  match 'get_lead_stages' => 'deals#get_lead_stages'
  match 'change_lead_stage' => 'deals#change_lead_stage'
  match 'change_lead_stage_in_lead_details' => 'deals#change_lead_stage_in_lead_details'
  match 'leads/kanban' => 'deals#index'
  match '/get_kanban_stages' => 'deals#get_kanban_stages', :via => [:post]
  match 'tab_settings_in_kanban' => 'deals#tab_settings_in_kanban', :via => [:post]

  

  authenticated :user do
    root :to => 'home#dashboard'
  end
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  match '/notfound' => 'home#notfound'

  match '/pricing' => 'home#index'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'
  match '/security' => 'home#security'
  match '/contact_us' => 'home#contact_us'
  match '/activities' => 'home#activities'
  match '/api_contact_us' => 'home#api_contact_us', :via => [:post]
  match '/bug_reports' => 'home#report_a_bug'
  match '/save_bug_report' => 'api#save_bug_report', :via => [:post]
  match '/show_bug_report/:id' => 'home#show_bug_report'
  match '/post_comment' => 'home#post_comment'
  match '/delete_emails' => 'deals#delete_emails'
  match '/archive_emails' => 'deals#archive_emails'

  get 'get_day_reminder' => 'reminders#get_day_reminder'
  get 'get_day_reminder' => 'home#dashboard'
  get 'dashboard' => 'home#dashboard', :as => 'dashboard'
  match '/task_widget' => 'home#task_widget'
  match '/lead_task_widget' => 'deals#deal_task_widget'
  match '/task_widget_reload' => 'deals#task_widget_reload'
  match '/get_activities' => 'home#get_activities'
  match '/usage' => 'home#usage'
  resources :contacts do
    get :autocomplete_first_name, :on => :collection

  end

  match 'add_contact_form' => 'contacts#add_contact_form', :via => [:post]
  match 'get_companies/:org_id' => 'application#get_companies'
  match 'company_contact/:id' => 'contacts#company_contact_detail'
  match 'individual_contact/:id' => 'contacts#individual_contact_detail'
  match 'contact/:id' => 'contacts#show_contact_detail'
  resources :contacts
  match 'contacts/change_status/:id' => 'contacts#change_status', :via => [:post]
  match 'get_all_contacts' => 'contacts#get_all_contacts', :via => [:GET]
  match 'get_more_contacts' => 'contacts#get_more_contacts', :via => [:post], :as => 'get_more_contacts'
  match 'contact_widget' => 'contacts#contact_widget', :via => [:post]
  match 'get_contact_ajax' => 'contacts#get_contact_ajax', :via => [:post]
  match 'save_contact_timezone' => 'contacts#save_contact_timezone'

  match 'imported_contacts' => 'contacts#imported_contacts', :via => [:get,:post] 
  match 'import_contact_from_sugar_crm' => 'contacts#import_contact_from_sugar_crm', :via => [:get,:post] 
  match 'import_contact_from_zoho_crm' => 'contacts#import_contact_from_zoho_crm', :via => [:get,:post] 
  match 'import_contact_from_fatfree_crm' => 'contacts#import_contact_from_fatfree_crm', :via => [:get,:post] 
  match 'import_contact_from_other_crm' => 'contacts#import_contact_from_other_crm', :via => [:get,:post] 
  match 'proceed_to_lead' => 'contacts#proceed_to_lead', :via => [:get] 
  match 'fetch_more_contacts' => 'contacts#fetch_more_contacts', :via => [:post], :as => 'get_more_contacts'
  
  resources :users
  match 'get_user_email' => 'users#get_user_email'
  match 'profile' => 'users#profile'
  match 'profile/:id' => 'users#profile'
  match 'assign_unassign_deals' => 'users#assign_unassign_deals', :via => [:post]
  match 'get_daily_update_form' => 'deals#get_daily_update_form', :via => [:get]
  match 'save_daily_updates' => 'users#save_daily_updates', :via => [:post]
  match 'manage_daily_updates' => 'users#manage_daily_updates'
  match 'edit_daily_update' => 'users#edit_daily_update'
  match 'delete_daily_update/:id' => 'users#delete_daily_update', :via => [:delete], :as => 'delete_daily_update'
  match '/create_admin_user' => 'users#create_admin_user', :via => [:post]

  match '/download_user' => 'home#download_user', :as => 'download_user'
  match 'source_list' => 'users#source_list', :as => 'source_list'
  match 'industry_list' => 'users#industry_list', :as => 'industry_list'
  match '/change_password' => 'users#change_password'
  match '/save_password' => 'users#save_password', :via => [:put]
  match 'invite_user' => 'users#invite_user'
  match 'invite_demo_user' => 'users#invite_demo_user'
  match 'get_source_list' => 'users#get_source_list', :via => [:post], :as => 'get_source_list'
  match 'get_industry_list' => 'users#get_industry_list', :via => [:post], :as => 'get_industry_list'
  match 'delete_source/:id' => 'users#delete_source'
  match 'delete_industry/:id' => 'users#delete_industry'
  match 'save_profile_info' => 'users#save_profile_info'
  match 'edit_user' => 'users#edit_user'
  match 'assign_deal_to_user' => 'users#assign_deal_to_user'
  match 'resend_invitation' => 'users#resend_invitation'
  match 'load_header_count_user' => 'users#load_header_count_user'
  match 'enable_user/:id' => 'users#enable_usr'
  match 'user_save_tmp_img' => 'users#save_tmp_img'
  match 'update_profile_image' => 'users#update_profile_image'
  match 'block_unblock_user' => 'users#block_unblock_user'
  match 'grant_revoke_admin' => 'users#grant_revoke_admin'
  match 'remove_lead' => 'users#remove_lead'

  resources :tasks
  match 'calendar_task' => 'tasks#calendar_task'
  match 'calendar_data' => 'tasks#calendar_data'
  match 'task_tab_data' => 'tasks#task_tab_data'

  match 'complete' => 'tasks#complete', :via => [:post]
  match 'edit_task' => 'tasks#edit_task'
  match 'follow_up_task' => 'tasks#follow_up_task'
  match 'start_task' => 'tasks#start_task', :via => [:post]
  match 'all_task' => 'tasks#all_task', :via => [:post]
  match 'today_task' => 'tasks#today_task', :via => [:post]
  match 'overdue_task' => 'tasks#overdue_task', :via => [:post]
  match 'upcoming_task' => 'tasks#upcoming_task', :via => [:post]
  match 'task_listing' => 'tasks#task_listing', :via => [:post]
  match 'task_filter' => 'tasks#task_filter', :via => [:post]

app/helpers/home_helper.rb
module HomeHelper

 ##Activites as per organization includes deals,contacts,tasks and notes
 def get_organization_activity_stream org_id
   activities = []
   org = Organization.find org_id
   activities << org.deals
   activities << org.deal_moves
   activities << org.contacts
   activities << org.tasks
   activities << org.attachments
   activities = activities.flatten.sort! { |x,y| y.created_at <=> x.created_at } 
 end

def activity_stream org_id, page =1, per_page=20
    #activities = Organization.find_by_sql("select id,'Organization' as name,created_at from organizations where id = "+org_id.to_s+"
    #UNION ALL
    #select id,'Deal' as name,created_at from deals where organization_id = "+org_id.to_s+"
    #UNION ALL
    #select id,'CompanyContact' as name,created_at from  company_contacts where organization_id = "+org_id.to_s+"
    #UNION ALL
    #select id,'IndividualContact' as name,created_at from individual_contacts where organization_id = "+org_id.to_s+"
    #UNION ALL
    #select id,'DealMove' as name,created_at from deal_moves where organization_id = "+org_id.to_s+"
    #UNION ALL
    #select id,'Task' as name,created_at from tasks where organization_id = "+org_id.to_s+"
    #UNION ALL
    #select id,'Note' as name,created_at from notes where organization_id = "+org_id.to_s+"
    #order by created_at desc limit " + per_page.to_s + " offset " + ((page-1)*per_page).to_s)
    
    
    activities = current_user.organization.activities.limit(per_page.to_s).offset(((page-1)*per_page).to_s).order("activity_date desc") 
  
   
    
  end
  
  
  def calculate_ratio_monthwise prev, current, prev_week, current_week
      avg_prev = (prev.to_f / prev_week.to_f)
      avg_cur = (current.to_f / current_week.to_f)
      if avg_prev!= 0
        result = ( avg_cur - avg_prev ) * 100 / avg_prev
      else
        result = ( avg_cur - avg_prev ) * 100 
      end
      result = result.nan? ? 0 : result
  end  
  
  def calculate_ratio_weekwise prev_week, current_week
    if prev_week != 0
      ( current_week.to_f - prev_week.to_f ) * 100 / prev_week.to_f
    else
      ( current_week.to_f - prev_week.to_f ) * 100
    end
  end

  def build_contact_us_info (email, name, comment, phone=nil,is_remote=false)
      contact = ContactUs.where(:email => email).first
      if contact.nil? || contact.blank?
           a = ContactUs.create :email => email , :is_remote => is_remote
           ContactUsInfo.create :name => name, :comment => comment, :phone => phone, :contact_us => a
      else
          ContactUsInfo.create :name => name, :comment => comment, :phone => phone, :contact_us => contact
      end
  end




end

app/views/home/_activities.haml
.box.span4{style: "margin-left:10px;height:600px"}
  %header
    %h5 Activities
    .toolbar
      /.btn-group
      /  %a.btn.btn-default.btn-sm.accordion-toggle.minimize-box{"data-toggle" => "collapse", href: "#activityTable"}
      /    %i.icon-chevron-up
  #activityTable.body.collapse.in{style: "height:550px"}
    =render :partial => "organization_activities"





app/views/home/_import_contact_modal.haml
#ImportContactModal.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
  .modal-dialog.cstm-material-modal
    .modal-content
      = form_tag("",method: "post",:multipart => true, class: "import_contact_form") do
        .modal-header
          %button.close{"aria-hidden" => "true", type: "button", "data-dismiss" => "modal"} x
          %h4.modal-title Import Contact
          .download_sample_csv{style: "display:none"}
            %p
              We are supporting csv file import. Here is a sample csv format we are supporting.
            %p
              Click Here to Download
              %a{href: "http://wakeupsales.com/contact.csv", download: "contact.csv", style: "text-decoration:underline;"} 
                Sample CSV
        .modal-body
          .row{:style => "margin-bottom:-35px;"}
            .form-group.col-md-12
              .choose_crm
                .col-md-6
                  %span  
                    %input{:checked => "checked", :name => "choose_crm", :onclick => "open_crm_modal('sugar_crm');show_crm_radio();", :type => "radio", style: "width: auto;display: inline-block;"}
                  %span  
                    = label_tag 'Sugar CRM'

                .col-md-6
                  %span
                    %input{:name => "choose_crm", :onclick => "open_crm_modal('fatfree_crm');show_crm_radio();", :type => "radio", style: "width: auto;display: inline-block;"}
                  %span  
                    = label_tag 'Fatfree CRM'

                .col-md-6
                  %span  
                    %input{ :name => "choose_crm", :onclick => "open_crm_modal('zoho_crm');show_crm_radio();", :type => "radio", style: "width: auto;display: inline-block;"}
                  %span  
                    = label_tag 'Zoho CRM'

                .col-md-6
                  %span  
                    %input{ :name => "choose_crm", :onclick => "open_crm_modal('other_crm');show_crm_radio();", :type => "radio", style: "width: auto;display: inline-block;"}
                  %span  
                    = label_tag 'Other CRM'

              = file_field_tag "attachment_lead", :class => "form-control", :required => true, style: "height: auto;"
              = hidden_field_tag "ref_site"
        .modal-footer{:style => "padding-bottom:16px;border:1px solid #ddd;"}
          .pull-right{:style => "margin-top:10px"}
            =submit_tag "Submit", :class=>"btn btn-primary btn-large", :disable_with => "Submitting....", :id => "submit_beta_user", :onclick=> "return chk_validemail('beta_account_email')"  

:javascript
  function open_crm_modal(crm_name){
    $(".choose_crm").hide();
    if(crm_name == "zoho_crm"){
      $("#ImportContactModal .modal-title").html("Import Contact From Zoho CRM");
      $("#ref_site").val("http://www.zohocrm.com");
      $(".import_contact_form").attr("action","/import_contact_from_zoho_crm");
      $(".download_sample_csv").hide();
    }
    if(crm_name == "sugar_crm"){
      $("#ImportContactModal .modal-title").html("Import Contact From Sugar CRM");
      $("#ref_site").val("http://www.sugarcrm.com");
      $(".import_contact_form").attr("action","/import_contact_from_sugar_crm");
      $(".download_sample_csv").hide();
    }
    if(crm_name == "fatfree_crm"){
      $("#ImportContactModal .modal-title").html("Import Contact From Fatfree CRM");
      $("#ref_site").val("http://www.fatfreecrm.com");
      $(".import_contact_form").attr("action","/import_contact_from_fatfree_crm");
      $(".download_sample_csv").hide();
    }
    if(crm_name == "other_crm"){
      $("#ImportContactModal .modal-title").html("Import Contact From Other CRM");
      $("#ref_site").val("Others");
      $(".import_contact_form").attr("action","/import_contact_from_other_crm");
      $(".download_sample_csv").show();
    }
  }

  function show_crm_radio(){
     $(".choose_crm").show(); 
  }

app/views/home/_line_chart.haml
.line_chart_div{style: "padding:0 10px;height: 439px;"}
  %div{style: "text-align:center;padding-top: 140px"}
    %img{alt: "Ajax-loader2", src: "#{ENV['cloudfront']}/assets/ajax-loader2.gif"}
    

app/views/home/_line_chart_display.haml
= high_chart("lineChart", @deal_line_chart)
#lineChart.body.collapse.in

app/views/home/_pie_chart.haml
.pie_chart_div{style: "padding:0 10px;"}
  %div{style: "text-align:center;padding-top: 60px"}
    %img{alt: "Ajax-loader2", src: "#{ENV['cloudfront']}/assets/ajax-loader2.gif"}
    


app/views/home/_pie_chart_display.haml
= high_chart("pieChart", @deal_bar_chart)
#pieChart.body.collapse.in

app/views/home/_pie_donut.haml
.pie_donut_chart_div{style: "padding:0 10px;"}
  %div{style: "text-align:center;padding-top: 60px"}
    %img{alt: "Ajax-loader2", src: "#{ENV['cloudfront']}/assets/ajax-loader2.gif"}

app/views/home/_siteadmin_dashboard.haml
.container
  .row
    .cb10
    .cb10
    .col-lg-12
      .con-box1
        %div      
          #task_header
            .box{style: "border:0"}
              .tabbable.task_tab
                %ul.nav.nav-tabs
                  %li.active
                    %a{"data-toggle" => "tab", href: "#beta_user_div"} Beta Users
                  /%li
                  /  %a{"data-toggle" => "tab", href: "#organization_div", onclick: "$('#range').trigger('change');"} Organizations
                .tab-content{style: "padding:10px 0px"}
                  #beta_user_div.tab-pane.active
                    = render :partial=>"betauser_list"
                  /#organization_div.tab-pane
                  /  %div
                  /    Organization list
                  /    /= render :partial=>"organization_list"
        .cb10

        = render :partial=>"beta_accounts/invite_beta_user"
      .cb10

:javascript
  $(document).ready(function() {    
    var activeSystemClass = $('.list-group-item.active');
    search_leaderboard()
    function search_leaderboard(){
      //something is entered in search form
      $('#system-search').keyup( function() {
         var that = this;
          // affect all table rows on in systems table
          var tableBody = $('.table-list-search tbody');
          var tableRowsClass = $('.table-list-search tbody tr');
          $('.search-sf').remove();
          tableRowsClass.each( function(i, val) {
          
              //Lower text for case insensitive
              var rowText = $(val).text().toLowerCase();
              var inputText = $(that).val().toLowerCase();
              if(inputText != '')
              {
                  $('.search-query-sf').remove();
                  tableBody.prepend('<tr class="search-query-sf"><td colspan="12"><strong>Searching for: "'
                      + $(that).val()
                      + '"</strong></td></tr>');
              }
              else
              {
                  $('.search-query-sf').remove();
              }

              if( rowText.indexOf( inputText ) == -1 )
              {
                  //hide rows
                  tableRowsClass.eq(i).hide();
                  
              }
              else
              {
                  $('.search-sf').remove();
                  tableRowsClass.eq(i).show();
              }
          });
          //all tr elements are hidden
          if(tableRowsClass.children(':visible').length == 0)
          {
              tableBody.append('<tr class="search-sf"><td class="text-muted" colspan="12">No entries found.</td></tr>');
          }
      });
    }
  });
  

app/views/home/_summary.haml
:javascript
  $(function(){
    $('a[rel="tooltip"],i,input:checkbox,button,div,span').powerTip({smartPlacement: true,fadeInTime: 100,fadeOutTime: 200});
  });
.count_nav_block.bggry
  .fl.count_total
    You Have
  .cb
.count_nav_block
  - task_call_count = Task.last_three_months.task_list(current_user,nil,nil,nil,'Call').count
  .fl.ic_t_call
  - if task_call_count > 0
    = link_to tasks_url(:type=>"all", :t_type=>@current_organization.task_types.where(:name => "Call").first.id), :style=>"color:#78808A" do
      .fl.count_total        
        Total Calls
      .fr.fnt30
        =task_call_count
  - else
    .fl.count_total        
      Total Calls
    .fr.fnt30
      =task_call_count 
  .cb
.count_nav_block.bggry
  - task_apointment_count = Task.last_three_months.task_list(current_user,nil,nil,nil,'Appointment').count
  .fl.ic_t_appo
  - if task_apointment_count > 0
    = link_to tasks_url(:type=>"all", :t_type=>@current_organization.task_types.where(:name => "Appointment").first.id), :style=>"color:#78808A" do
      .fl.count_total
        Total Appointments
      .fr.fnt30    
        =task_apointment_count
  - else
    .fl.count_total
      Total Appointments
    .fr.fnt30    
      =task_apointment_count
  .cb
/.count_nav_block
/  .fl.ic_t_outs
/  .fl.count_total.txtblue
/    Outstanding Tasks
/  .fr.fnt30.txtblue
/    - if badge_overdue  > 0
/      = link_to tasks_url(:type=>"overdue"), :style=>"color:#49AFCD" do
/        =badge_overdue
/    - else
/      =badge_overdue
/  .cb
/.count_nav_block.bggry
/  .fl.ic_t_upcom
/  .fl.count_total.txtgrn
/    Upcoming Tasks
/  .fr.fnt30.txtgrn
/    - if badge_upcoming > 0
/      = link_to tasks_url(:type=>"upcoming"), :style=>"color:#4F8E50" do
/        =badge_upcoming
/    - else
/      =badge_upcoming
/  .cb
.count_nav_block
  .fl.ic_t_lead
  - if new_deals_three_month > 0
    = link_to leads_url(:type=>"incoming", :daterange => "3m"), :onclick => "document.cookie='dt_range=3m';",:style=>"color:#78808A" do
      .fl.count_total
        Leads to nurture
      .fr.fnt30
        = new_deals_three_month
  - else
    .fl.count_total
      Leads to nurture
    .fr.fnt30
      = new_deals_three_month
    /- if @current_user.is_super_admin? || @current_user.is_admin?
    /  - if new_deals_three_month > 0
    /    = link_to deals_url(:type=>"incoming"), :style=>"color:#78808A" do
    /      =new_deals_three_month
    /  - else
    /    = new_deals_three_month
    /- else
    /  - if new_deals_three_month > 0
    /    = link_to deals_url(:assigned_to=>@current_user.id), :style=>"color:#78808A" do
    /      =new_deals_three_month
    /  - else
        
  .cb
.count_nav_block
  .fl.ic_l_deal
  .fl.count_total
    - if @last_deal.present?
      - tooltip_text = ("#{@last_closed_deal.title}").html_safe
      = link_to lead_url(@last_closed_deal), style: "font-size:15px", rel: "tooltip", title: "#{tooltip_text}" do
        Last lead close
    - else
      Last lead closed
    - if @last_deal.present?
      %br
      %span{style: "font-size:13px"} 
        By: 
        = @last_closed_user
  .fr.fnt30
    - if @last_deal.present?
      - tooltip_text = ("#{@last_closed_deal.title}").html_safe
      = link_to lead_url(@last_closed_deal), style: "font-size:15px", rel: "tooltip", title: "#{tooltip_text}" do
        /= truncate(@last_closed_deal.title, :length => 15, :omission => '...')
        = @last_close_deal_date
    - else
      %span{style: "font-size:15px"}
        Yet to close a lead.
  .cb
.count_nav_block
  .fl.ic_t_outs
  .fl.count_total
    Avg time to close a lead
    %span{style:"font-size:14px;font-style:italic"} (in days)
  .fr.fnt30
    - if @last_deal.present? && @ratio.present?
      = @ratio.to_i
    - else
      %span{style: "font-size:15px"}
        Yet to close a lead.
  .cb

app/views/home/reminders.haml
.container
  .row
    .cb10
    .cb10
    .col-md-12
      .col-md-8
        %div
          / Trigger the modal with a button
          %button.btn.btn-info.btn-lg{"data-target" => "#reminderModal", "data-toggle" => "modal", :type => "button"} Add Reminder

          = render :partial => "reminders_calendar"
      .col-md-4
        %div{:style=>"border:1px solid red;width:100px;height:100px;"}
      .cb

/ Reminder Modal
#reminderModal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Add Reminder
      - @reminder = Reminder.new
      = form_for(@reminder, :url => reminders_path, :remote => true, :html=>{:class => "form",:method=> "Post",:id=> "reminder_form"}) do |f|
        .modal-body
          = render "reminder_form", :f => f
        .modal-footer
          =f.submit "Save", :class=> "btn btn-primary", :disable_with => "Please wait ...",:onclick=> "return validate_email('task_mail_to')"
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
:javascript
  var newdate = new Date();
  $('#reminder_reminder_date').datetimepicker(
    {
      minDate: newdate, 
      useCurrent: false,  
      format: 'MM-DD-YYYY HH:mm'
    }
  )

  $('input.reminder_types').on('change', function() {
      $('input.reminder_types').not(this).prop('checked', false);
      var reminder_type_id = $('input.reminder_types:checked').val();
      alert(reminder_type_id)
      $("#reminder_reminder_type_id").val(reminder_type_id);
  });

  $('.reminder_deal_typeahead').typeahead([{
    name: 'deals',
    valueKey: 'deal_name',
    remote: {url: '/get_leads/'+ #{current_user.organization.id}+ '?q=%QUERY'},
    template: '<p><strong>{{deal_name}}</strong></p>',
    engine: Hogan
    }]).on('typeahead:selected',onSelectedTask).on('typeahead:opened',onOpened);
   
  function onSelectedTask($e,datum){
    var dfield = document.getElementById('dfield');
    $('#lead').val(datum.id)
    dfield.value = datum.id;    
  }

  function onOpened($e){
    $("#dfield").val("")
  }
   
  function onClosed($e){
    if($("#dfield").val() == ""){
      $("#reminder_lead").val("");
    }
  }

  $('#reminder_form').bind('ajax:success', function(evt, data, status, xhr){
    $('#reminderModal').hide();
  });

  $('#reminder_form').bind('ajax:before', function(evt, data, status, xhr){
    $('#task_loader').show();
  });