config/routes.rb
SalesCafe::Application.routes.draw do
  resources :reminders

  get 'home/index'
  match 'users/sign_up' => 'home#index', :via => [:get]
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks",:passwords => "passwords"}
  

  match "/contacts/:importer/contact_callback" => 'contacts#contact_callback', :via => [:get, :post]
  match 'import_contacts' => 'contacts#import_contacts', :via => [:get, :post]

  match '/contacts/failure' => 'contacts#import_failure'
  resources :settings
  post 'settings/save_group' => 'settings#save_group'
  post 'settings/delete_group' => 'settings#delete_group'
  post 'settings/delete_label' => 'settings#delete_label'
  post 'settings/get_group' => 'settings#get_group'
  post 'settings/save_source' => 'settings#save_source', :as => 'save_source'
  post 'settings/save_industry' => 'settings#save_industry', :as => 'save_industry'
  post 'settings/save_label' => 'settings#save_label', :as => 'save_label'
  post 'settings/save_user_label' => 'settings#save_user_label', :as => 'save_label'
  post 'settings/get_user_label' => 'settings#get_user_label'
  post 'settings/get_task_outcome_label' => 'settings#get_task_outcome_label'
  post 'settings/save_task_outcome_label' => 'settings#save_task_outcome_label'
  post 'settings/delete_taskoutcome' => 'settings#delete_taskoutcome'

  match '/update_weekly_digest' => 'settings#update_weekly_digest', :via => [:get, :post]
  match '/unscribe_latest_blog' => 'settings#unscribe_latest_blog', :via => [:get, :post]
  match 'settings/update_priority_org' => 'settings#update_priority_org', :via => [:get, :post]
  match 'settings/update_lead_status' => 'settings#update_deal_status', :via => [:get, :post]
  match 'settings/update_feed_keyword_org' => 'settings#update_feed_keyword_org', :via => [:get, :post]
  match 'settings/update_widget_org' => 'settings#update_widget_org', :via => [:get, :post]
  match 'settings/update_notification' => 'settings#update_notification', :via => [:get, :post]
  match 'settings/fetch_pages' => 'settings#fetch_pages', :via => [:get, :post]
  match 'update_org_settings' => 'settings#update_org_settings'
  match 'get_contacts/:org_id' => 'application#get_contacts'
  match 'settings/edit_source' => 'settings#edit_source'
  match 'settings/edit_industry' => 'settings#edit_industry'
  match 'edit_company_contact/:id' => 'contacts#edit_company_contact'
  match 'edit_individual_contact/:id' => 'contacts#edit_individual_contact'
  match 'getting_started' => 'home#getting_started'
  match 'daily_updates' => 'home#daily_updates'  
  match 'clear_cache' => 'home#clear_cache'
  match 'load_header_count_section' => 'home#load_header_count_section'
  match 'pie_donut_chart' => 'home#pie_donut_chart'
  match 'line_chart_display' => 'home#line_chart_display'
  match 'summary' => 'home#summary'
  match 'lead_statistics_info' => 'home#deal_statistics_info'
  match 'pie_chart_display' => 'home#pie_chart_display'
  match 'task_widget_page' => 'home#task_widget_page'
  match 'header_user_info' => 'application#header_user_info'
  match 'load_all_partials' => 'application#load_all_partials'
  match 'lead_contacts_info' => 'deals#deal_contacts_info'
  match 'created_by_user' => 'deals#created_by_user'
  match 'lead_location_filter' => 'deals#deal_location_filter'
  match 'assigned_lead_leaderboard' => 'deals#assigned_deal_leaderboard'
  match 'upload_multiple_note_attach' => 'deals#upload_multiple_note_attach'
  match 'delete_temp_note_attach' => 'deals#delete_temp_note_attach'
  match 'send_weekly_digest_email' => 'deals#send_weekly_digest_email'
  match 'leads/change_lead_status' => 'deals#change_lead_status'
  match 'get_lead_details_in_lead_listing' => 'deals#get_lead_details_in_lead_listing'
  match 'change_priority' => 'deals#change_priority'
  match 'change_user_label' => 'deals#change_user_label'
  match 'add_attchment_to_lead' => 'deals#add_attchment_to_lead'
  match 'get_lead_stages' => 'deals#get_lead_stages'
  match 'change_lead_stage' => 'deals#change_lead_stage'
  match 'change_lead_stage_in_lead_details' => 'deals#change_lead_stage_in_lead_details'
  match 'leads/kanban' => 'deals#index'
  match '/get_kanban_stages' => 'deals#get_kanban_stages', :via => [:post]
  match 'tab_settings_in_kanban' => 'deals#tab_settings_in_kanban', :via => [:post]

  

  authenticated :user do
    root :to => 'home#dashboard'
  end
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  match '/notfound' => 'home#notfound'

  match '/pricing' => 'home#index'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'
  match '/security' => 'home#security'
  match '/contact_us' => 'home#contact_us'
  match '/activities' => 'home#activities'
  match '/api_contact_us' => 'home#api_contact_us', :via => [:post]
  match '/bug_reports' => 'home#report_a_bug'
  match '/save_bug_report' => 'api#save_bug_report', :via => [:post]
  match '/show_bug_report/:id' => 'home#show_bug_report'
  match '/post_comment' => 'home#post_comment'
  match '/delete_emails' => 'deals#delete_emails'
  match '/archive_emails' => 'deals#archive_emails'

  get 'get_day_reminder' => 'reminders#get_day_reminder'
  get 'get_day_reminder' => 'home#dashboard'
  get 'dashboard' => 'home#dashboard', :as => 'dashboard'
  match '/task_widget' => 'home#task_widget'
  match '/lead_task_widget' => 'deals#deal_task_widget'
  match '/task_widget_reload' => 'deals#task_widget_reload'
  match '/get_activities' => 'home#get_activities'
  match '/usage' => 'home#usage'
  resources :contacts do
    get :autocomplete_first_name, :on => :collection

  end

  match 'add_contact_form' => 'contacts#add_contact_form', :via => [:post]
  match 'get_companies/:org_id' => 'application#get_companies'
  match 'company_contact/:id' => 'contacts#company_contact_detail'
  match 'individual_contact/:id' => 'contacts#individual_contact_detail'
  match 'contact/:id' => 'contacts#show_contact_detail'
  resources :contacts
  match 'contacts/change_status/:id' => 'contacts#change_status', :via => [:post]
  match 'get_all_contacts' => 'contacts#get_all_contacts', :via => [:GET]
  match 'get_more_contacts' => 'contacts#get_more_contacts', :via => [:post], :as => 'get_more_contacts'
  match 'contact_widget' => 'contacts#contact_widget', :via => [:post]
  match 'get_contact_ajax' => 'contacts#get_contact_ajax', :via => [:post]
  match 'save_contact_timezone' => 'contacts#save_contact_timezone'

  match 'imported_contacts' => 'contacts#imported_contacts', :via => [:get,:post] 
  match 'import_contact_from_sugar_crm' => 'contacts#import_contact_from_sugar_crm', :via => [:get,:post] 
  match 'import_contact_from_zoho_crm' => 'contacts#import_contact_from_zoho_crm', :via => [:get,:post] 
  match 'import_contact_from_fatfree_crm' => 'contacts#import_contact_from_fatfree_crm', :via => [:get,:post] 
  match 'import_contact_from_other_crm' => 'contacts#import_contact_from_other_crm', :via => [:get,:post] 
  match 'proceed_to_lead' => 'contacts#proceed_to_lead', :via => [:get] 
  match 'fetch_more_contacts' => 'contacts#fetch_more_contacts', :via => [:post], :as => 'get_more_contacts'
  
  resources :users
  match 'get_user_email' => 'users#get_user_email'
  match 'profile' => 'users#profile'
  match 'profile/:id' => 'users#profile'
  match 'assign_unassign_deals' => 'users#assign_unassign_deals', :via => [:post]
  match 'get_daily_update_form' => 'deals#get_daily_update_form', :via => [:get]
  match 'save_daily_updates' => 'users#save_daily_updates', :via => [:post]
  match 'manage_daily_updates' => 'users#manage_daily_updates'
  match 'edit_daily_update' => 'users#edit_daily_update'
  match 'delete_daily_update/:id' => 'users#delete_daily_update', :via => [:delete], :as => 'delete_daily_update'
  match '/create_admin_user' => 'users#create_admin_user', :via => [:post]

  match '/download_user' => 'home#download_user', :as => 'download_user'
  match 'source_list' => 'users#source_list', :as => 'source_list'
  match 'industry_list' => 'users#industry_list', :as => 'industry_list'
  match '/change_password' => 'users#change_password'
  match '/save_password' => 'users#save_password', :via => [:put]
  match 'invite_user' => 'users#invite_user'
  match 'invite_demo_user' => 'users#invite_demo_user'
  match 'get_source_list' => 'users#get_source_list', :via => [:post], :as => 'get_source_list'
  match 'get_industry_list' => 'users#get_industry_list', :via => [:post], :as => 'get_industry_list'
  match 'delete_source/:id' => 'users#delete_source'
  match 'delete_industry/:id' => 'users#delete_industry'
  match 'save_profile_info' => 'users#save_profile_info'
  match 'edit_user' => 'users#edit_user'
  match 'assign_deal_to_user' => 'users#assign_deal_to_user'
  match 'resend_invitation' => 'users#resend_invitation'
  match 'load_header_count_user' => 'users#load_header_count_user'
  match 'enable_user/:id' => 'users#enable_usr'
  match 'user_save_tmp_img' => 'users#save_tmp_img'
  match 'update_profile_image' => 'users#update_profile_image'
  match 'block_unblock_user' => 'users#block_unblock_user'
  match 'grant_revoke_admin' => 'users#grant_revoke_admin'
  match 'remove_lead' => 'users#remove_lead'

  resources :tasks
  match 'calendar_task' => 'tasks#calendar_task'
  match 'calendar_data' => 'tasks#calendar_data'
  match 'task_tab_data' => 'tasks#task_tab_data'

  match 'complete' => 'tasks#complete', :via => [:post]
  match 'edit_task' => 'tasks#edit_task'
  match 'follow_up_task' => 'tasks#follow_up_task'
  match 'start_task' => 'tasks#start_task', :via => [:post]
  match 'all_task' => 'tasks#all_task', :via => [:post]
  match 'today_task' => 'tasks#today_task', :via => [:post]
  match 'overdue_task' => 'tasks#overdue_task', :via => [:post]
  match 'upcoming_task' => 'tasks#upcoming_task', :via => [:post]
  match 'task_listing' => 'tasks#task_listing', :via => [:post]
  match 'task_filter' => 'tasks#task_filter', :via => [:post]

app/helpers/deals_helper.rb
module DealsHelper

 def get_deal_activity_stream_new deal_id
     deal = Deal.find(deal_id)
     activities = deal.activities.where("organization_id = ?", current_user.organization.id).order("activity_date desc")

 end
 

 
 def get_deal_activity_stream deal_id
   activities = []
   deal = Deal.includes([:tasks,:deal_moves]).find(deal_id)
   activities << deal
   activities << deal.tasks
   #activities << deal.attachments.includes([:user])
   activities << deal.deal_moves
   
   deal.deal_moves.includes([:attachment]).each do |deal_move|
    activities << deal_move.attachment if deal_move.attachment.present?
   end
   activities = activities.flatten.sort! { |x,y| y.created_at <=> x.created_at}
 end
 
 
 def last_activity(deal_id)
  activity=get_deal_activity_stream(deal_id).first
  last_updated_by=""
  if(activity.class.name == "Deal")
    user=User.where("id=?",activity.initiated_by).first
    last_updated_by="me" if user.present? && user.id==current_user.id
    last_updated_by = activity.initiator.full_name if activity.present? && activity.initiator.present? 
  elsif(activity.class.name == "DealMove")
    last_updated_by=(activity.user_id) == current_user.id ? "me" : (activity.user.present? ? activity.user.full_name : "")
  else
    user=User.where("id=?",activity.created_by).first
    last_updated_by="me" if user.present? && user.id==current_user.id
    last_updated_by = activity.user.full_name if activity.user.present?
  end
  return get_activity_timing(activity), last_updated_by
 end

def last_activity_show(deal_id)
  activity=get_deal_activity_stream(deal_id).first
  last_updated_by=""
  if(activity.class.name == "Deal")
    user=User.where("id=?",activity.initiated_by).first
    last_updated_by="me" if user.present? && user.id==current_user.id
    last_updated_by = activity.initiator.full_name if activity.present? && activity.initiator.present? 
  elsif(activity.class.name == "DealMove")
    last_updated_by=(activity.user_id) == current_user.id ? "me" : (activity.user.present? ? activity.user.full_name : "")
  else
    user=User.where("id=?",activity.created_by).first
    last_updated_by="me" if user.present? && user.id==current_user.id
    last_updated_by = activity.user.full_name if activity.user.present?
  end
  return get_activity_timing_show(activity), last_updated_by
 end
 
 def last_activity_show_new(deal_id)
    deal = Deal.includes(:activities).find(deal_id) 
    activity= deal.activities.where("organization_id = ?", current_user.organization.id).order("activity_date desc").first
    if activity.present?
       user=User.where("id=?",activity.activity_user_id).first
       if user.present? 
         last_updated_by=(activity.activity_user_id) == current_user.id ? "me" : (activity.user.present? ? activity.user.full_name : "")    
    
       end
     return distance_of_time_in_words_to_now(activity.activity_date), last_updated_by
    end
 
 end
 
 def get_activity_timing(activity)
  activity.created_at.strftime("%b %d, %Y @ %I:%M %p")
 end
 
def get_activity_timing_show(activity)
  distance_of_time_in_words_to_now activity.created_at
 end
 
 def get_file_type_img(type)
    data = type.scan(/\.\w+$/)
   case data[0]
     when ".jpg" 
       return "/assets/jpgimg.png"
     when  '.jpeg'
       return "/assets/jpgimg.png"  
     when ".doc" 
       return "/assets/docimg.png"
	 when ".DOC" 
       return "/assets/docimg.png"
     when  ".docx"
       return "/assets/docimg.png"  
     when ".xls" 
       return "/assets/xlsimg.png"
     when ".xlsx"
       return "/assets/xlsimg.png"  
     when ".ppt" 
       return "/assets/pptimg.png"   
     when  ".pptx"
       return "/assets/pptimg.png"   
     when ".pdf"
       return "/assets/pdfimg.png"
     when ".png"
       return "/assets/pngimg.png"
     when ".txt"
       return "/assets/txtimg.png"
	 when ".html"
       return "/assets/htmlimg.png"
	 when ".htm"
       return "/assets/htmlimg.png"	
	 when ".mp4"
       return "/assets/mp4img.png"	   
	 when ".mp3"
       return "/assets/mp3img.png"	   
   else
     return "/assets/fileimg.png"
   end
 end
 def last_activity_for_deal_json(deal,user)
  activity=get_deal_activity_stream(deal).first
  current_user = user
  title = ""
  last_updated_by=""
#  if(activity.class.name == "Task")
#    
#    activity.title
#    last_updated_by=(user=User.find(activity.created_by)).id == current_user.id ? "me" : activity.user.full_name
#  elsif(activity.class.name == "Note")
#    activity.notes
#    last_updated_by=(user=User.find(activity.created_by).id) == current_user.id ? "me" : activity.user.full_name
  if(activity.class.name == "Deal")

#     deal.title
    last_updated_by=""
    if activity.initiated_by.present?
      user=User.where("id=?",activity.initiated_by).first
      if user.present? && user.id == current_user.id
         last_updated_by = "me"


      elsif activity.initiator.present?
        activity.initiator.full_name
      end
    end
    #(user_name=User.find(activity.initiated_by).id) == current_user.id ? "me" : activity.initiator.full_name
#  elsif(activity.class.name == "Contact")
#    if activity.contact_type == "Company"
#        name = "#{activity.name}" + ", " + "#{activity.full_name}"
#      else
#        name = "#{activity.full_name}"
#      end
#    (user_name=User.find(contact.created_by).id) == current_user.id ? "me" : contact.initiator.full_name
  elsif(activity.class.name == "DealMove")
#     activity.deal.title

    last_updated_by=(activity.user_id) == current_user.id ? "me" : (activity.user.present? ? activity.user.full_name : "")
  else

    
    last_updated_by=""
    if activity.created_by.present?
      user=User.where("id=?",activity.created_by).first
      if user.present? && user.id == current_user.id
         last_updated_by = "me"


      elsif activity.user.present?
        activity.user.full_name
      end
    end
  #last_updated_by=(user=User.find(activity.created_by)).id == current_user.id ? "me" : activity.user.full_name
  end
  return get_activity_timing(activity), last_updated_by, get_activity_timing_show(activity)
 end

 def last_activity_for_deal_json_new(deal,user)
#  deal = Deal.includes(:activities).find(deal) #.order("activity_date desc").first
  #activity = Activity.select("activity_date").where(:source_id => deal).last
  #activity=get_deal_activity_stream_new(deal).first
  # activity= deal.activities.where("organization_id = ?", user.organization.id).last
  # if activity.present?
    # distance_of_time_in_words_to_now activity.activity_date
  # end
  if deal.last_activity_date.present?
   distance_of_time_in_words_to_now deal.last_activity_date 
  end
 end

  def get_current_quarter(date)    
    quarters = [1, 2, 3, 4]
    quarters[(date.month - 1) / 3]     
  end
 
  def calculate_win_percentage total, won
   result = ((((won.to_f / total.to_f)) * 100)/3).to_f
   result = result.nan? ? 0 : result.round(2)
   
  end
end

app/views/deals/_activity_stream.haml
.container
  .row
    .panel.panel-default.widget
      .panel-heading
        %span.glyphicon.glyphicon-comment
        %h3.panel-title
          Activity Stream
        /%span.label.label-info
        /  = @contact.attachments.count
      .panel-body
        %ul.list-group
          / - if !@contact.attachments.nil? && !@contact.attachments.blank?
          /  - @contact.attachments.order("created_at desc").each do |attachment|
          - activities = get_deal_activity_stream(@deal.id)
          - activities.each do |activity|
            / *********** Notes
            /=activity.class.name
            -if(activity.class.name == "Note")
              -attachment = activity
              %li.list-group-item
                .row
                  .col-xs-2.col-md-1
                    - if !attachment.user.image.nil?
                      - img_path = attachment.user.image.image.url(:icon)
                    - else
                      - img_path = "/assets/no_user.png"
                    %img.img-circle.img-thumbnail.img-responsive{alt: "", src: img_path}/
                  .col-xs-8.col-md-10
                    %div
                      %span.linkspan
                        = attachment.notes
                      .mic-info
                        By:
                        %span.linkspan
                          /= attachment.user.name
                          =#{(attachment.created_by == current_user.id ? "me" : attachment.user.full_name}
                      .mic-info
                        Created
                        = format_date(attachment.created_at)                        
                    
                  .col-xs-2.col-md-1      
                    %h5
                      %span.label.label-warning
                        Notes
            / *********** DealMove
            -if(activity.class.name == "DealMove")
              -dealmove = activity
              %li.list-group-item
                .row
                  .col-xs-2.col-md-1
                    - if !dealmove.user.image.nil?
                      - img_path = dealmove.user.image.image.url(:icon)
                    - else
                      - img_path = "/assets/no_user.png"
                    %img.img-circle.img-thumbnail.img-responsive{alt: "", src: img_path}/
                  .col-xs-8.col-md-10
                    %div
                      %span.linkspan
                        = dealmove.attachment.notes
                      .mic-info
                        By:
                        %span.linkspan
                          #{dealmove.user.id == current_user.id ? "me" : dealmove.user.full_name}
                      .mic-info
                        Created
                        = format_date(dealmove.created_at)                        
                    
                  .col-xs-2.col-md-1      
                    %h5
                      %span.label.label-success
                        =dealmove.deal_status.name   
            / *********** Task
            -if(activity.class.name == "Deal")
              -deal = activity
              %li.list-group-item
                .row
                  .col-xs-2.col-md-1
                    - if !deal.assigned_user.image.nil?
                      - img_path = deal.assigned_user.image.image.url(:icon)
                    - else
                      - img_path = "/assets/no_user.png"
                    %img.img-circle.img-thumbnail.img-responsive{alt: "", src: img_path}/
                  .col-xs-8.col-md-10
                    %div
                      = link_to deal.title, lead_path(deal)
                      .mic-info
                        By:
                        %span.linkspan
                          #{(user_name=User.find(deal.initiated_by).id) == current_user.id ? "me" : deal.initiator.full_name}
                          /= deal.initiator.full_name
                        
                      .mic-info
                        Created
                        = format_date(deal.created_at)                        
                    
                  .col-xs-2.col-md-1      
                    %h5
                      %span.label.label-danger.labe_imp
                        Deal
            / *********** Task
            -if(activity.class.name == "Task")
              -task = activity
              %li.list-group-item
                .row
                  .col-xs-2.col-md-1
                    - if !task.user.image.nil?
                      - img_path = task.user.image.image.url(:icon)
                    - else
                      - img_path = "/assets/no_user.png"
                    %img.img-circle.img-thumbnail.img-responsive{alt: "", src: img_path}/
                  - if task.is_completed
                    - style_text="text-decoration:line-through; "
                  .col-xs-8.col-md-10{style: style_text}
                    %div
                      %a{href: "javascript:"}
                        - deal= Deal.find(task.deal_id)
                        = link_to deal.title+" / "+task.title, lead_path(deal)
                        /= task.title
                      .mic-info
                        Assigned To:
                        %span.linkspan
                          = task.user.full_name
                        &nbsp;&nbsp;
                        %b • 
                        Created By:
                        #{(user_name=User.find(task.created_by).id) == current_user.id ? "me" : task.initiator.full_name}
                        &nbsp;&nbsp;
                        %b • 
                        %span.due_date
                          Due on  #{task.due_date.strftime("%a %d %b %Y @ %H:%M") if task.due_date.present?}
                      .mic-info
                        Created
                        = format_date(task.created_at)                        
                    
                  .col-xs-2.col-md-1      
                    %h5
                      %span.label.label-info.pull-left
                        Task  
          /- else
          /  %li.list-group-item
          /    No data found !!!
        /%a.btn.btn-primary.btn-sm.btn-block{href: "#", role: "button"}
        /  %span.glyphicon.glyphicon-refresh
        /  More

        

app/views/deals/_get_stages.haml
- all_stages = @current_organization.deal_statuses
- if @page == "lead_listing"
  - all_stages.each do |stage|
    %li{onclick: "changeLeadStage(#{@lead.id}, #{stage.id})"}
      = stage.name
    %li.divider
- elsif @page == "lead_details"
  - all_stages.each do |stage|
    %li{onclick: "changeLeadStageInLeadDetails(#{@lead.id}, #{stage.id})"}
      = stage.name
    %li.divider
:javascript
  function changeLeadStage(id, stage_id,page){
    $("#task_loader").show();
    $.ajax({
      url: "/change_lead_stage",
      data: {id: id,stage_id: stage_id,page: page},
      success: function(data){ 
        //alert("Success");
        $(".lead-stages-cntr .lead-"+id).html(data);
        $("#task_loader").hide();
      },
      error: function(data){
        $("#task_loader").hide();
        alert('Got an error while changing priority.');
      }
    });
  }

  function changeLeadStageInLeadDetails(id, stage_id){
    $("#task_loader").show();
    $.ajax({
      url: "/change_lead_stage_in_lead_details",
      data: {id: id,stage_id: stage_id},
      success: function(data){ 
        $(".lead-details-page .deal_status_name").html(data);
        $(".lead-details-page .deal_status_name").attr("tooltipText",data);
        $("#task_loader").hide();
      },
      error: function(data){
        $("#task_loader").hide();
        alert('Got an error while changing priority.');
      }
    });
  }

app/views/deals/new.haml
%link{href: asset_path("lib/tagsinput/jquery.tagsinput"), rel: "stylesheet"}
%script{src: asset_path("lib/tagsinput/jquery.tagsinput.min")}
.box 
  -@deal=Deal.new
  -if(!params[:contact_id].nil?)
    -@deal.contact = Contact.find params[:contact_id]
  -else
    -@deal.contact = Contact.new
  = form_for(@deal, url: new_lead_path, :html=>{:class => "form",:multipart => true, :method=>"post",:id=>"edit_deal"}) do |f|
    %header
      .icons
        %i.icon-pencil
      %h5 EDIT LEAD
    .container
      =hidden_field_tag :allnew,"true"
      =hidden_field_tag "deal[contact_id]",@deal.contact.id
      =render :partial=>"editdeal",:locals=>{:f => f}
      -@contact = (!@deal.contact.nil? ? @deal.contact : Contact.new)
      =render :partial=>"shared/edit_contact",:locals=>{:f => f}
      .row
        .col-md-8
          %button.btn.btn-primary{type: "submit"} Save
          
:javascript
  //history.replaceState({}, '', '/deals/new'); 

  $(function() {     
    
    $('#editable_source').editable({
      url: '/settings/save_source' ,
      pk: 1,
      title: 'Enter Source',
      type: 'text',
      data: {custom: 'text'}, 
      text: "+NEW",
      validate: function(value) {
        if($.trim(value) == '')
          return 'Please enter Source name';
      },
      success: function(data) {
        
        var newsource = data.split('-');
        var o = new Option(newsource[0],newsource[0]);
        /// jquerify the DOM object 'o' so we can use the html method
        
        $(o).html(newsource[1]);
        
        $(o).prop('selected', true)
        $("#deal_deal_source").append(o);
        //$("#editable_source").text("+NEW");
        //alert($("#editable_source").text());
      },
      error: function(data) {
        /* actions on validation error (or ajax error) */
        var msg = '';
        if(data.errors) { //validation error
          $.each(data.errors, function(k, v) { msg += k+": "+v+"<br>"; });
        } 
        else if(data.responseText) { //ajax error
        msg = data.responseText;
      }
    }
    });
    
    $('#editable_source').on('hidden', function(e, editable) {
      $("#editable_source").text("+ NEW");
      editable.text = "";
    });
    // Save industry
    $('#editable_industry').editable({
      url: '/settings/save_industry' ,
      pk: 1,
      title: 'Enter Industry',
      type: 'text',
      data: {custom: 'text'}, 
      text: "+NEW",
      validate: function(value) {
        if($.trim(value) == '')
          return 'Please enter industry name';
      },
      success: function(data) {
        
        var newsource = data.split('-');
        var o = new Option(newsource[0],newsource[0]);
        /// jquerify the DOM object 'o' so we can use the html method
        
        $(o).html(newsource[1]);
        
        $(o).prop('selected', true)
        $("#deal_deal_industry").append(o);
        //$("#editable_industry").text("+NEW");
        //alert($("#editable_industry").text());
      },
      error: function(data) {
        /* actions on validation error (or ajax error) */
        var msg = '';
        if(data.errors) { //validation error
          $.each(data.errors, function(k, v) { msg += k+": "+v+"<br>"; });
        } 
        else if(data.responseText) { //ajax error
        msg = data.responseText;
      }
    }
    });
    
    $('#editable_industry').on('hidden', function(e, editable) {
      $("#editable_industry").text("+ NEW");
      editable.text = "";
    });
    
  });
  $(function() { 
  $('#deal_tags').tagsInput({'defaultText':'Click to add'});
  });
