config/routes.rb
  match '/unscribe_latest_blog' => 'settings#unscribe_latest_blog', :via => [:get, :post]
  match 'settings/update_priority_org' => 'settings#update_priority_org', :via => [:get, :post]
  match 'settings/update_lead_status' => 'settings#update_deal_status', :via => [:get, :post]
  match 'settings/update_feed_keyword_org' => 'settings#update_feed_keyword_org', :via => [:get, :post]
  match 'settings/update_widget_org' => 'settings#update_widget_org', :via => [:get, :post]
  match 'settings/update_notification' => 'settings#update_notification', :via => [:get, :post]
  match 'settings/fetch_pages' => 'settings#fetch_pages', :via => [:get, :post]
  match 'update_org_settings' => 'settings#update_org_settings'
  match 'get_contacts/:org_id' => 'application#get_contacts'
  match 'settings/edit_source' => 'settings#edit_source'
  match 'settings/edit_industry' => 'settings#edit_industry'
  match 'edit_company_contact/:id' => 'contacts#edit_company_contact'
  match 'edit_individual_contact/:id' => 'contacts#edit_individual_contact'
  match 'getting_started' => 'home#getting_started'
  match 'daily_updates' => 'home#daily_updates'  
  match 'clear_cache' => 'home#clear_cache'
  match 'load_header_count_section' => 'home#load_header_count_section'
  match 'pie_donut_chart' => 'home#pie_donut_chart'
  match 'line_chart_display' => 'home#line_chart_display'
  match 'summary' => 'home#summary'
  match 'lead_statistics_info' => 'home#deal_statistics_info'
  match 'pie_chart_display' => 'home#pie_chart_display'
  match 'task_widget_page' => 'home#task_widget_page'
  match 'header_user_info' => 'application#header_user_info'
  match 'load_all_partials' => 'application#load_all_partials'
  match 'lead_contacts_info' => 'deals#deal_contacts_info'
  match 'created_by_user' => 'deals#created_by_user'
  match 'lead_location_filter' => 'deals#deal_location_filter'
  match 'assigned_lead_leaderboard' => 'deals#assigned_deal_leaderboard'
  match 'upload_multiple_note_attach' => 'deals#upload_multiple_note_attach'
  match 'delete_temp_note_attach' => 'deals#delete_temp_note_attach'
  match 'send_weekly_digest_email' => 'deals#send_weekly_digest_email'
  match 'leads/change_lead_status' => 'deals#change_lead_status'
  match 'get_lead_details_in_lead_listing' => 'deals#get_lead_details_in_lead_listing'
  match 'change_priority' => 'deals#change_priority'
  match 'change_user_label' => 'deals#change_user_label'
  match 'add_attchment_to_lead' => 'deals#add_attchment_to_lead'
  match 'get_lead_stages' => 'deals#get_lead_stages'
  match 'change_lead_stage' => 'deals#change_lead_stage'
  match 'change_lead_stage_in_lead_details' => 'deals#change_lead_stage_in_lead_details'
  match 'leads/kanban' => 'deals#index'
  match '/get_kanban_stages' => 'deals#get_kanban_stages', :via => [:post]
  match 'tab_settings_in_kanban' => 'deals#tab_settings_in_kanban', :via => [:post]

  

  authenticated :user do
    root :to => 'home#dashboard'
  end
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  match '/notfound' => 'home#notfound'

  match '/pricing' => 'home#index'
  match '/terms' => 'home#terms'
  match '/privacy' => 'home#privacy'
  match '/security' => 'home#security'
  match '/contact_us' => 'home#contact_us'
  match '/activities' => 'home#activities'
  match '/api_contact_us' => 'home#api_contact_us', :via => [:post]
  match '/bug_reports' => 'home#report_a_bug'
  match '/save_bug_report' => 'api#save_bug_report', :via => [:post]
  match '/show_bug_report/:id' => 'home#show_bug_report'
  match '/post_comment' => 'home#post_comment'
  match '/delete_emails' => 'deals#delete_emails'
  match '/archive_emails' => 'deals#archive_emails'

  get 'get_day_reminder' => 'reminders#get_day_reminder'
  get 'get_day_reminder' => 'home#dashboard'
  get 'dashboard' => 'home#dashboard', :as => 'dashboard'
  match '/task_widget' => 'home#task_widget'
  match '/lead_task_widget' => 'deals#deal_task_widget'
  match '/task_widget_reload' => 'deals#task_widget_reload'
  match '/get_activities' => 'home#get_activities'
  match '/usage' => 'home#usage'
  resources :contacts do
    get :autocomplete_first_name, :on => :collection

  end

  match 'add_contact_form' => 'contacts#add_contact_form', :via => [:post]
  match 'get_companies/:org_id' => 'application#get_companies'
  match 'company_contact/:id' => 'contacts#company_contact_detail'
  match 'individual_contact/:id' => 'contacts#individual_contact_detail'
  match 'contact/:id' => 'contacts#show_contact_detail'
  resources :contacts
  match 'contacts/change_status/:id' => 'contacts#change_status', :via => [:post]
  match 'get_all_contacts' => 'contacts#get_all_contacts', :via => [:GET]
  match 'get_more_contacts' => 'contacts#get_more_contacts', :via => [:post], :as => 'get_more_contacts'
  match 'contact_widget' => 'contacts#contact_widget', :via => [:post]
  match 'get_contact_ajax' => 'contacts#get_contact_ajax', :via => [:post]
  match 'save_contact_timezone' => 'contacts#save_contact_timezone'

  match 'imported_contacts' => 'contacts#imported_contacts', :via => [:get,:post] 
  match 'import_contact_from_sugar_crm' => 'contacts#import_contact_from_sugar_crm', :via => [:get,:post] 
  match 'import_contact_from_zoho_crm' => 'contacts#import_contact_from_zoho_crm', :via => [:get,:post] 
  match 'import_contact_from_fatfree_crm' => 'contacts#import_contact_from_fatfree_crm', :via => [:get,:post] 
  match 'import_contact_from_other_crm' => 'contacts#import_contact_from_other_crm', :via => [:get,:post] 
  match 'proceed_to_lead' => 'contacts#proceed_to_lead', :via => [:get] 
  match 'fetch_more_contacts' => 'contacts#fetch_more_contacts', :via => [:post], :as => 'get_more_contacts'
  
  resources :users
  match 'get_user_email' => 'users#get_user_email'
  match 'profile' => 'users#profile'
  match 'profile/:id' => 'users#profile'
  match 'assign_unassign_deals' => 'users#assign_unassign_deals', :via => [:post]
  match 'get_daily_update_form' => 'deals#get_daily_update_form', :via => [:get]
  match 'save_daily_updates' => 'users#save_daily_updates', :via => [:post]
  match 'manage_daily_updates' => 'users#manage_daily_updates'
  match 'edit_daily_update' => 'users#edit_daily_update'
  match 'delete_daily_update/:id' => 'users#delete_daily_update', :via => [:delete], :as => 'delete_daily_update'
  match '/create_admin_user' => 'users#create_admin_user', :via => [:post]

  match '/download_user' => 'home#download_user', :as => 'download_user'
  match 'source_list' => 'users#source_list', :as => 'source_list'
  match 'industry_list' => 'users#industry_list', :as => 'industry_list'
  match '/change_password' => 'users#change_password'
  match '/save_password' => 'users#save_password', :via => [:put]
  match 'invite_user' => 'users#invite_user'
  match 'invite_demo_user' => 'users#invite_demo_user'
  match 'get_source_list' => 'users#get_source_list', :via => [:post], :as => 'get_source_list'
  match 'get_industry_list' => 'users#get_industry_list', :via => [:post], :as => 'get_industry_list'
  match 'delete_source/:id' => 'users#delete_source'
  match 'delete_industry/:id' => 'users#delete_industry'
  match 'save_profile_info' => 'users#save_profile_info'
  match 'edit_user' => 'users#edit_user'
  match 'assign_deal_to_user' => 'users#assign_deal_to_user'
  match 'resend_invitation' => 'users#resend_invitation'
  match 'load_header_count_user' => 'users#load_header_count_user'
  match 'enable_user/:id' => 'users#enable_usr'
  match 'user_save_tmp_img' => 'users#save_tmp_img'
  match 'update_profile_image' => 'users#update_profile_image'
  match 'block_unblock_user' => 'users#block_unblock_user'
  match 'grant_revoke_admin' => 'users#grant_revoke_admin'
  match 'remove_lead' => 'users#remove_lead'

  resources :tasks
  match 'calendar_task' => 'tasks#calendar_task'
  match 'calendar_data' => 'tasks#calendar_data'
  match 'task_tab_data' => 'tasks#task_tab_data'

  match 'complete' => 'tasks#complete', :via => [:post]
  match 'edit_task' => 'tasks#edit_task'
  match 'follow_up_task' => 'tasks#follow_up_task'
  match 'start_task' => 'tasks#start_task', :via => [:post]
  match 'all_task' => 'tasks#all_task', :via => [:post]
  match 'today_task' => 'tasks#today_task', :via => [:post]
  match 'overdue_task' => 'tasks#overdue_task', :via => [:post]
  match 'upcoming_task' => 'tasks#upcoming_task', :via => [:post]
  match 'task_listing' => 'tasks#task_listing', :via => [:post]
  match 'task_filter' => 'tasks#task_filter', :via => [:post]
  match 'fetch_tasks' => 'tasks#fetch_tasks', :via => [:get]

  match 'get_task_type' => 'tasks#get_task_type'
  match 'change_task_type' => 'tasks#change_task_type'

  match '/get_sqllite_task' => 'tasks#get_sqllite_task'
  match 'get_inactive_leads' => 'deals#get_inactive_deals'

  resources :deals, path: :leads, as: :leads
  match 'leads/move_lead' => 'deals#move_deal', :via => [:post], :as => 'move_lead'
  match 'leads/apply_label_to_lead' => 'deals#apply_label_to_deal', :via => [:post]
  match 'leads/apply_label_to_single_lead' => 'deals#apply_label_to_single_deal', :via => [:post]
  match 'leads/setting' => 'deals#deal_setting', :via => [:post]
  match 'get_incoming_leads' => 'deals#get_incoming_deals', :via => [:post], :as => 'get_incoming_leads'
  match 'get_working_on_leads' => 'deals#get_working_on_deals', :via => [:post], :as => 'get_working_on_leads'
  match 'get_won_leads' => 'deals#get_won_deals', :via => [:post], :as => 'get_won_leads'
  match 'get_lost_leads' => 'deals#get_lost_deals', :via => [:post], :as => 'get_lost_leads'
  match 'get_junk_leads' => 'deals#get_junk_deals', :via => [:post], :as => 'get_junk_leads'
  match 'get_un_assigned_leads' => 'deals#get_un_assigned_deals', :via => [:post], :as => 'get_un_assigned_leads'
  match 'get_other_leads' => 'deals#get_other_deals', :via => [:post], :as => 'get_other_leads'

  match 'get_contact' => 'deals#get_contact', :via => [:post]
  match 'edit_lead' => 'deals#edit_deal', :via => [:post]

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :organization
  belongs_to :company_strength
  has_many :deals, :dependent => :nullify
  has_one :address, :as => :addressable,:class_name=>"Address", :dependent => :destroy
  has_many :phones, :as => :phoneble, :dependent => :destroy
  has_one :image,:class_name=>"Image",:as=>:imagable, :dependent => :destroy
  has_many :attachments,:class_name=>"Note",:as=>:notable, :dependent => :destroy
  has_many :tasks, :as=> :taskable, :dependent => :destroy
  belongs_to :initiator,:class_name=>"User",:foreign_key=>"created_by"
    
  #include Tire::Model::Search
  #include Tire::Model::Callbacks
  
 # mapping do
  #  indexes :title,      type: 'string'
   # indexes :image_url
    #indexes :initiator_name
    #indexes :phone_number
    #indexes :country_name
  #end
  
#  def to_indexed_json
#    to_json(:methods => [:title, :image_url])
#  end
  ### Export CSV ###
  def self.to_csv(org_id,cont_country=nil)
    org = Organization.find_by_id org_id
    @all_contacts = org.individual_contacts + org.company_contacts

    if cont_country.present?
      filter_ind_contacts = org.individual_contacts.where("country_id =?", cont_country)
      filter_com_contacts = org.company_contacts.where("country_id =?", cont_country)
      @all_contacts = filter_ind_contacts + filter_com_contacts
    end

    p @all_contacts
    @contacts = @all_contacts.sort_by{|e| e[:created_at]}
    CSV.generate do |csv|
      csv << ["Name", "Email", "Country", "Type", "Last Touch", "Leads", "Tasks", "Last Lead", "Last Task"] ## Header values of CSV
      @contacts.each do |contact|
        if contact.class.name == "IndividualContact"
          cont_type = "individual"
        else
          cont_type = "company"
        end
        csv << [cont_type == "company" ? contact.name : contact.full_name,
                contact.email, 
                contact.country.present? ? contact.country.name : "NA",
                cont_type,
                contact.updated_at,
                contact.deals_contacts.count,
                contact.tasks.count,
                contact.deals_contacts.present? && contact.deals_contacts.last.deal.present? ? contact.deals_contacts.last.deal.title : "NA",
                contact.tasks.last.present? ? contact.tasks.last.title : "NA"] ##Row values of CSV
      end
    end
  end

  def to_indexed_json
    to_json( 
      #:only   => [ :id, :name, :normalized_name, :url ],
      :methods   => [:title, :image_url, :initiator_name, :phone_number, :country_name]
    )
  end
  
  def image_url
    if self.image.present?
      image.image.url(:icon)
    else
      "/assets/no_user.png"
    end
  end
  
  def initiator_name
    initiator.present? ? initiator.full_name : ""
  end
  
  def phone_number
    phones.present? ? phones.first.phone_no : ""
  end
  
  def country_name
    address.present? && address.country.present? ? address.country.name : ""
  end
  attr_accessible :created_by, :email, :facebook_url, :first_name, :is_public, :last_name, :linkedin_url, :messanger_id, 
              :messanger_type, :name, :twitter_url, :website,:organization,:organization_id,:company_strength_id,:contact_type,:created_at
              
              
  attr_accessor :country,:work_phone,:contact_id,:note,:file_description,:attachment,  :city,
          :state, :zip_code,:mobile_number,:contact_image, :full_address
          
  
  scope :by_contact_type, lambda{|type| where("contact_type = ? ", type)}  
  scope :by_organization_id, lambda{|org_id| where("organization_id = ? ", org_id)}  
  ## disabled public deals view by normal user
  #scope :by_visibilty, lambda{|org_id,user_id| where("organization_id = ? and (is_public = true or (is_public = false and created_by=?))", org_id,user_id) }  
  scope :by_visibilty, lambda{|org_id,user_id| where("organization_id = ? and (created_by=?)", org_id,user_id) }   
  scope :search_by, lambda{|data| where("name REGEXP ? or first_name REGEXP ? or last_name REGEXP ? or email REGEXP ?", data,data, data,data)}         
  scope :by_first_letter,   lambda{|type| where("first_name like '"+type+"%' " )}  
  scope :by_first_letter_name,   lambda{|type| where("name like '"+type+"%' " )}  
  scope :by_alpha_firstname,   lambda{where("first_name REGEXP '^[^A-Za-z]' " )}  
  scope :by_alpha_name,   lambda{ where("name REGEXP '^[^A-Za-z]' ")}  
          
  def full_name
    "#{first_name} #{last_name}"
  end
  
  ##for dasboard activity 
  def title
    "#{first_name} #{last_name}"
  end

  def self.get_color_code char
    if(["a","e","i","m"].include?(char.to_s))
      color = "#F4511E"
    elsif(["c","g","k","o","r"].include?(char.to_s))
      color = "#CCCC65"
    elsif(["d","h","l"].include?(char.to_s))
      color = "#9575CD"
    elsif(["p","s"].include?(char.to_s))
      color = "#FFA726"
    elsif(["t","u","v","w"].include?(char.to_s))
      color = "#4FC3F7"
    elsif(["b","f","j","n","q"].include?(char.to_s))
      color = "#FF8A65"
    elsif(["x","y","z"].include?(char.to_s))
      color = "#A1887F"
    end
    return color
  end
  
end

app/helpers/reports_helper.rb
module ReportsHelper

  def startdate_enddate_range quarter
      if(quarter == "1")
        start_date = DateTime.new(Time.zone.now.year,1)
        end_date = DateTime.new(Time.zone.now.year,3)     
      elsif(quarter == "2")
        start_date = DateTime.new(Time.zone.now.year,4)
        end_date = DateTime.new(Time.zone.now.year,6)     
      elsif(quarter == "3")
        start_date = DateTime.new(Time.zone.now.year,7)
        end_date = DateTime.new(Time.zone.now.year,9)     
      elsif(quarter == "4")
        start_date = DateTime.new(Time.zone.now.year,10)
        end_date = DateTime.new(Time.zone.now.year,12)     
      end
      return start_date, end_date
  end

  ##for activity count in leader dashboard
  def get_user_activity_count_for_leaderboard(user, start_date, end_date)
     ##start_date = DateTime.new(Time.zone.now.year,10)
     ##end_date = DateTime.new(Time.zone.now.year,12)  
     # activities=Task.find_by_sql("select count(*) count , created_by from (select id,'Deal' as name,created_at,initiated_by created_by from deals where organization_id = #{user.organization.id}  AND initiated_by = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}'
    #UNION ALL
    #(select id,'Contact' as name,created_at,created_by from contacts where organization_id = #{user.organization.id} AND created_by = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}')
    #UNION ALL
    #(select id,'DealMove' as name,created_at,created_by from notes where notable_type = 'DealMove' and organization_id =  #{user.organization.id} AND created_by = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}')
    #UNION ALL
    #(select id,'Task' as name,created_at,created_by from tasks where organization_id = #{user.organization.id} AND created_by = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}')
    #UNION ALL
    #(select id,'Task' as name,updated_at as created_at,assigned_to created_by from tasks where is_completed=1 and organization_id =  #{user.organization.id}  AND assigned_to = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}')
    #UNION ALL
    #(select id,'Note' as name,created_at,created_by from notes where organization_id =  #{user.organization.id} AND created_by = #{user.id} AND created_at BETWEEN '#{start_date}' AND '#{end_date}')
	#UNION ALL
   # (select id,'Mail' as name,created_at,mail_by created_by  from mail_letters where organization_id =  #{user.organization.id} AND mail_by = #{user.id}  AND created_at BETWEEN '#{start_date}' AND '#{end_date}')) activities

#group by created_by order by count(*) desc")
 #   activities
    activities=user.activities.by_range(start_date,end_date).count
    activities
  
  end






end

app/views/reports/_deals_won_list.haml
.table-responsive
  %table.table.white-table.table-hover.table-striped
    %thead
      %tr
        %th Title
        %th Won Date
        %th Assigned To
        %th Created By
        %th Amount($)
    %tbody

      - if !@deals.nil? || !@deals.blank?
        - @deals.each do |deal|
          %tr
            %td 
              = link_to deal.title, lead_path(deal.id)
            %td
              = date_format(deal.deal_moves.first.created_at)
            %td 
              - if deal.assigned_user.present?
                - value=((deal.assigned_user.id == current_user.id) ? "me" : deal.assigned_user.full_name)
                - url="/profile/#{deal.assigned_user.id}"
              -else
                - value='NA'
                - url="javascript:"
              = link_to value, url
            %td
              - if deal.initiator.present?
                - value=((deal.initiator.id == current_user.id) ? "me" : deal.initiator.full_name)
                - url="/profile/#{deal.initiator.id}"
              -else
                - value='NA'
                - url="javascript:"
              = link_to value, url
            %td
              = (deal.amount.present? ? deal.amount : "NA")
              
      
            


app/views/reports/_lead_age_bar_chart.haml
= high_chart("bar_tag_chart", @bar_tag_chart)
#bar_tag_chart.body.collapse.in

app/views/reports/_leaderboard_list.haml
.table-responsive
  %table.table.white-table.table-hover.table-striped
    %thead
      %tr
        %th Name
        %th Group
        %th Deals assigned
        %th Deals Won
        %th 
          Total Revenue($)
        %th 
          Avg. time
          %i  (in days)
        %th Activity
        %th Task assigned
        %th Task completed   
        %th Overdue tasks
        
    %tbody
      - if !@users.nil? || !@users.blank?
        - @users.each do |user|
          %tr
            %td 
              /=link_to user.full_name, edit_user_path(user)
              = user.full_name
              /= user.id
            %td 
              - if user.admin_type == 1
                Super Admin
              - elsif user.admin_type == 2
                Admin
              -elsif user.user_role.present? && user.user_role.role.present?
                = user.user_role.role.name
            %td 
              /= user.all_assigned_deal.by_range(@start_date,@end_date).count
              /- assigned_deal = user.all_assigned_deal.by_range(@start_date,@end_date).includes(:deal_status).where("deal_statuses.original_id IN (?)", [1]).count   
              /- assigned_deal = user.all_assigned_deal.by_range(@start_date,@end_date).where(:is_active=>true,:deal_status_id=>user.organization.incoming_deal_status().id).count
              - new_deal_piedonut=user.all_assigned_deal.includes(:deal_status).by_range(@start_date,@end_date).where("deals.deal_status_id IS NOT NULL").group("deal_statuses.original_id").count
              - assigned_deal = new_deal_piedonut.values.sum
              - if assigned_deal != 0 
                /= link_to deals_url(:assigned_to=>user.id, :q=>@quarter,:y=>@year) do
                = link_to "javascript:", :onclick=>"display_assigned_deal_user(\'#{user.id}\',\'#{@start_date.to_date}\',\'#{@end_date.to_date}\' )" do
                  = assigned_deal
              - else
                = assigned_deal
            %td 
              = get_deal_status_won_count(user,[4],@start_date,@end_date).count
            %td 
              = user.all_assigned_deal.by_range(@start_date,@end_date).joins(:deal_status).where(:is_active=>true).where("deal_statuses.original_id IN (?) ", [4]).select('sum(amount) as total_revenue').first.total_revenue
            %td 
              = Deal.find_avg_deal_close_ratio_status_won user.id, user.organization.id, @start_date.strftime("%Y-%m-%d"),@end_date.strftime("%Y-%m-%d")
            %td 
              = get_user_activity_count_for_leaderboard user, @start_date, @end_date
            %td 
              - taskassigned = user.all_tasks_assigned.by_range(@start_date,@end_date).count
              - if taskassigned > 0
                = link_to tasks_url(:type=>"all", :assigned_to=>user.id, :q=>@quarter ,:y=>@year  ) do
                  = taskassigned
              - else
                = taskassigned
            %td 
              - taskcompleted = user.all_tasks_assigned.by_range(@start_date,@end_date).by_is_completed.count
              - if taskcompleted > 0
                = link_to tasks_url(:type=>"completed", :assigned_to=>user.id, :q=>@quarter ,:y=>@year  ) do
                  = user.all_tasks_assigned.by_range(@start_date,@end_date).by_is_completed.count
              - else
                = taskcompleted
            %td 
              - taskoverdue = user.all_tasks_assigned.by_range(@start_date,@end_date).where("is_completed=? AND DATE_FORMAT(DATE_ADD(due_date, INTERVAL #{Time.zone.now.utc_offset} second), '%Y/%m/%d') < ? ", false, @end_date.strftime("%Y/%m/%d")).count
              - if taskoverdue > 0
                = link_to tasks_url(:type=>"overdue", :assigned_to=>user.id, :q=>@quarter ,:y=>@year  ) do
                  = taskoverdue
              - else
                = taskoverdue

            


app/views/reports/_pie_tag_chart.haml
= high_chart("pie_tag_chart", @pie_tag_chart)
#pie_tag_chart.body.collapse.in

app/views/reports/_sales_analytic.haml
.table-responsive
  %table.table.white-table.table-hover.table-striped
    %thead
      %tr
        %th Name
        %th Group
        %th Deals assigned
        %th Call
        %th Email
        %th Follow-up
        %th Quote
        %th Appointment
        %th Qualified
        %th Won
        /%th 
        /  Deals
        /  %i{style: "font-size: 11px;"}  (Not Qual. + Lost)
        %th Lost
        %th Junk

    %tbody
      - if !@users.nil? || !@users.blank?
        - @users.each do |user|
          - total_deal=user.all_assigned_deal.by_is_active.includes(:deal_status).by_range(@start_date,@end_date).where("deals.deal_status_id IS NOT NULL").group("deal_statuses.original_id").count
          %tr
            %td 
              = user.full_name
            %td 
              - if user.admin_type == 1
                Super Admin
              - elsif user.admin_type == 2
                Admin
              -elsif user.user_role.present? && user.user_role.role.present?
                = user.user_role.role.name
            %td 
              - assigned_deal = total_deal.values.sum
              - if assigned_deal != 0 
                = link_to "javascript:", :onclick=>"display_assigned_deal_user(\'#{user.id}\',\'#{@start_date.to_date}\',\'#{@end_date.to_date}\' )" do
                  = assigned_deal
              - else
                = assigned_deal
            - deal_ids = user.all_assigned_deal.by_is_active.by_range(@start_date,@end_date).select("id").map(&:id)
            - all_task = Task.select("id").where(taskable_id: deal_ids).where(taskable_type: "Deal").by_is_completed
            %td 
              = all_task.by_name("Call").count
            %td 
              = all_task.by_name("Email").count
            %td 
              = all_task.by_name("Follow-up").count
            %td 
              = all_task.by_name("Quote").count
            %td 
              = all_task.by_name("Appointment").count
            %td 
              = total_deal.values_at(2).first.nil? ? 0 :  total_deal.values_at(2).first
            %td 
              = total_deal.values_at(4).first.nil? ? 0 :  total_deal.values_at(4).first
            %td 
              - notq = total_deal.values_at(3).first.nil? ? 0 :  total_deal.values_at(3).first
              - lost = total_deal.values_at(5).first.nil? ? 0 :  total_deal.values_at(5).first
              = notq.to_i + lost.to_i
            %td 
              = total_deal.values_at(6).first.nil? ? 0 :  total_deal.values_at(6).first

            


app/views/reports/_sales_funnel_chart.haml

=javascript_include_tag "funnel"
=javascript_include_tag "exporting"
.col-lg-12.con-box1{style: "border-top:none;border-radius:0;background:#fff"}
  .col-lg-8
    = high_chart("funnel_chart", @funnel_chart)
  .cb	
#funnel_chart.body.collapse.in

.col-lg-4{style: "position:absolute;left: 60%; top: 30%"}
  .row.rpadding
    .panel.panel-default
      .panel-body{style: "padding: 10px 20px;"}
        .row.rpadding{style: "font-size: 12px;"}
          %b New Deals:
          - if @new_deals > 0
            = link_to leads_url(:type=>"incoming", :q=>@quarter ,:y=>@year ) do
              = @new_deals
          - else
            = @new_deals
        .row.rpadding{style: "font-size: 12px;"}
          %b  Qualified Deals:
          - if @qualified_deals > 0
            = link_to leads_url(:type=>"qualify", :q=>@quarter ,:y=>@year ) do
              = @qualified_deals
          - else
            = @qualified_deals
        .row.rpadding{style: "font-size: 12px;"}
          %b  Lost Deals:
          - if @lost_deals > 0
            = link_to leads_url(:type=>"lost", :q=>@quarter ,:y=>@year ) do
              = @lost_deals
          - else
            = @lost_deals
        .row.rpadding{style: "font-size: 12px;"}
          %b  Won Deals:
          - if @won_deals > 0
            = link_to leads_url(:type=>"won", :q=>@quarter ,:y=>@year ) do
              =@won_deals
          - else
            = @won_deals
.cb
%br
= render :partial => "tag_chart_view"